# HUD Part 2 Implementation Plan (Phase 5 of 5)

> **For agentic workers:** REQUIRED SUB-SKILL: Use superpowers:subagent-driven-development (recommended) or superpowers:executing-plans to implement this plan task-by-task. Steps use checkbox (`- [ ]`) syntax for tracking.

**Goal:** Finish the approved HUD by:
- adding the docked `SidePanel`, whose pane follows the selected building (Admissions, academic, dorm, dining, or under construction), in place of `InfoPanel`
- adding the `BuildPanel` and `ActionBar` in place of `BuildMenu`
- adding alerts and campus markers
- binding the remaining keys: B, X, Tab, F2 and F3
- extending `hud <name>` to every pane

**Architecture.**
- State answers every number, as in phase 4. This phase adds the stepper commands on `Policy`, building roles, what opening a building would change, the refund rule, and categories in the building DB.
- Two small pure UI models carry logic worth testing: `BuildingText` (how a type is worded) and `AlertFeed` (which alerts show). Views are scene-authored and poll state in `_process` while visible.
- `Hud` owns the routing. It opens popovers, shows a building's pane (selecting it and moving the camera there), opens the build panel on a category, and reads the keys.

**Tech Stack:** Godot 4.7, fully typed GDScript, gdUnit4, LimboConsole + TCP remote console.

**Spec:** `docs/superpowers/specs/2026-09-22-students-money-hud-design.md`, sections **HUD** (`SidePanel`, `BuildPanel`, `ActionBar`, Alerts, Campus markers, Keys) and **Phases → 5**.

**Visual reference:** `docs/superpowers/specs/2026-09-22-hud-mockup.html`. Match its:
- `#side` and its `.pane`s (`#pane-admissions`, `#pane-acad`, `#pane-dorm`, `#pane-uc`, `#pane-dining`)
- `.actions`
- `#build` (`.buildp`)
- `.alerts`
- `.marker`

Its CSS (`<style>` block) holds every size and colour. The design documents win over the mockup (for example, no demand anywhere).

## Global Constraints

- **Paths.** Repo root `/Users/noel/Development/University/game`; the Godot project is `university/`, and `res://` is `university/`.
- **`CLAUDE.md` governs.**
  - camelCase variables and functions; PascalCase classes, constants and signals.
  - `if (x):` with parentheses.
  - Fully typed GDScript. The following are all errors: unsafe property access, unsafe method access, unsafe call arguments, shadowing, integer division, `shadowed_global_identifier`, `int_as_enum_without_match` and `static_called_on_instance`.
    - A local or parameter named like a member, a method, a native class or a global fails to parse. Examples: `load`, `size`, `position`, `name`, `Separator`.
    - So does dividing two ints. `@warning_ignore("integer_division")` is the only accepted way to keep an int division.
    - Never read a field off an untyped Variant (`Array.back()`). Index the array instead.
    - A parse error silently drops that whole suite from the gdUnit total.
  - No magic numbers (named `const`). TAB indentation. No duplicate logic. Surgical changes.
  - **UI layout lives in `.tscn`**: anchors, offsets, margins, sizes, and fonts and colours through the theme. Code only sets:
    - dynamic text
    - visibility
    - a theme variation for a state-dependent tone
    - dynamic offsets (the alerts' shift, marker positions)
    - variable-count rows
  - **Use `%UniqueName`** for scene nodes. To reach into a sub-scene instance, use that instance's script API.
- **State classes** (`src/state/`, `src/data/`) have no Node, no Input and no views. Views read state and call its commands; state never calls views.
- **Colours only through `ui_theme.tres`.** Never author a literal `Color` in a `.tscn` or a script. Add a theme type variation instead, as phase 4 did with `StatusDot`, `SlotBadge`, `SlotSeparator` and `MenuItemDotted`.
  - A StyleBoxFlat has one `border_color`. For an edge in a different colour (the mockup's coloured left or right borders), use a thin Panel strip with its own variation, as the popup's accent does.
  - Bump `load_steps` whenever you add sub_resources. It must equal the ext_resources plus the sub_resources plus 1.
- **Every toned base has all five variants** (base, Good, Warn, Bad, Dim), because `UiTone.variation(base, tone)` can ask for any of them. That applies to any new base that a script tones through `UiTone`.
- **HUD buttons take no keyboard focus** (`focus_mode = 0`).
- **Components:**
  - `KpiView.display(value, caption, tone = Normal)`, from `kpi.tscn`
  - `InfoRow.display(key, value, note = "", tone = Normal)` and `showPill(text, tone)`, from `info_row.tscn`; `InfoRow.ValueBase` is `"RowValue"`
  - `MeterBar.setValue(fraction, tone, marks: Array[float], limit)`, with `MeterBar.NoLimit`
  - `SlotView`
  - `UiTone.Tone { Normal, Good, Warn, Bad, Dim }`, `UiTone.variation`, `UiTone.trend`
  - `MoneyFormat.short`, `signed`, `full`, and `NumberFormat.count`, `percent`
- **Pattern to follow.** The phase 4 dropdowns (`university/src/ui/students_dropdown.gd`, `housing_dropdown.gd`, `money_dropdown.gd`) show the house style:
  - every displayed string is a named const
  - `_process` returns early unless visible and set up
  - variable rows rebuild on `visibility_changed` (and on `University.SemesterStarted` where content changes), freeing old rows with `remove_child` + `queue_free` and keeping any header nodes
- **Palette** (for new variations; the theme's `Palette/colors/*` holds these):
  - `chrome` `Color(0.078, 0.094, 0.118)`, `chrome2` `Color(0.125, 0.149, 0.184)`, `chrome3` `Color(0.165, 0.196, 0.239)`
  - `line` `Color(1, 1, 1, 0.09)`, `line2` `Color(1, 1, 1, 0.16)`
  - `text` `Color(0.925, 0.906, 0.859)`, `muted` `Color(0.604, 0.643, 0.690)`, `dim` `Color(0.420, 0.459, 0.502)`
  - `gold` `Color(0.851, 0.643, 0.255)`, `gold2` `Color(0.941, 0.788, 0.416)`, `onGold` `Color(0.102, 0.078, 0.031)`
  - `good` `Color(0.388, 0.741, 0.447)`, `warn` `Color(0.886, 0.663, 0.227)`, `bad` `Color(0.886, 0.353, 0.306)`, `info` `Color(0.353, 0.655, 0.878)`
- **Fonts** in the theme (ext_resources already there):
  - Barlow Regular, Medium, SemiBold and Bold
  - Barlow Semi Condensed Medium, SemiBold and Bold
  - Cormorant (`SerifBold` FontVariation)

  Reuse existing ext_resource ids. Look them up in `ui_theme.tres`.
- **Verified 4.7 APIs** (probed headless on 2026-09-23): `Camera3D.unproject_position`, `Camera3D.is_position_behind`, `Control.set_anchors_preset`, `Label.text_overrun_behavior`, `Label.autowrap_mode`, `Control.tooltip_text`, `ScrollContainer.horizontal_scroll_mode`, `Button.clip_text`, and Button's `alignment`, `icon_alignment`, `vertical_icon_alignment` and `expand_icon`. gdUnit's `assert_vector(v).is_equal_approx(expected, Vector2(e, e))` is already used in the tests.
- **Remote console facts:**
  - `eval …get_global_rect()` prints nothing, so read `.global_position` and `.size` separately.
  - `find_child(name, true, false)` returns the first match in the tree. Several scenes reuse names such as `HousingButton` and `Title`, so reach a node through its parent: `find_child("SidePanel", true, false).find_child("DemolishButton", true, false)`.
  - The screenshot is 3840×2160. Synthetic mouse coordinates are in design space, 1920×1080.
- **Tests** assert behaviour and relationships, never data or tuning values. Views are verified by screenshots.
- **Commits** go to `main`, locally; never push. Commit `.gd.uid`, `.tscn`, `.import` and new SVG files next to their sources. Every message ends with `Co-Authored-By: Claude <the model you actually are> <noreply@anthropic.com>`.

### Named procedures

**REGISTER** (after adding or removing any `class_name` script or `.tscn`):
```
/Applications/Godot.app/Contents/MacOS/Godot --path /Users/noel/Development/University/game/university --headless --editor --quit-after 20 2>&1 | grep -E "ERROR|WARNING|Parse Error" ; true
```
Expected: no output.

**IMPORT** (after adding SVG icons):
```
/Applications/Godot.app/Contents/MacOS/Godot --path /Users/noel/Development/University/game/university --headless --import 2>&1 | grep -E "ERROR|WARNING" ; true
```

**RUN-TESTS:**
```
/Applications/Godot.app/Contents/MacOS/Godot --path /Users/noel/Development/University/game/university -s addons/gdUnit4/bin/GdUnitCmdTool.gd --add tests/ 2>&1 | sed 's/\x1b\[[0-9;]*m//g' | grep -E "Overall Summary|Executed test|FAILED|Parse Error|SCRIPT ERROR|leaked"
```
The run must show `0 errors | 0 failures`, and nothing may say `leaked`.

| After task | Cases | Suites |
|---|---|---|
| start | 210 | 20 |
| 1 | 222 | 20 |
| 2 | 228 | 22 |
| 3–9 | 228 | 22 |

**LAUNCH-CHECK:**
```
cd /Users/noel/Development/University/game
mkdir -p /tmp/university
(for i in $(seq 1 20); do sleep 0.2; osascript -e 'tell application "System Events" to set visible of process "Godot" to false' 2>/dev/null; done) &
./bin/run.sh > /tmp/university/run.log 2>&1 &
sleep 7
grep -nE "SCRIPT ERROR|Parse Error|ERROR|WARNING" /tmp/university/run.log
# console: echo "<command>" | nc -w 10 localhost 9999   (sleep 0.3 before a screenshot that should show an effect)
echo screenshot | nc -w 10 localhost 9999
pkill -f "Godot"
```
The grep must print nothing. LOOK at `/tmp/university/screenshot.png` with the Read tool (crop it with PIL if a region is small), compare it with the mockup, and say what you saw. Run `pause` first whenever reading numbers.

**Console.** `hud <name>` opens a popover (`gamemenu`, `unimenu`, `students`, `housing`, `money`, `reputation`), shows `popup`, or closes with `none`. This phase adds `build` (Task 6) and the panes `construction` (Task 3), `admissions` (Task 4), `academic`, `dorm` and `dining` (Task 5). The other commands are `build <id> <x> <z> <deg>`, `select <n>`, `buildings`, `state`, `pause`, `advance <months>`, `money`, `borrow`, `mousedown|mouseup <x> <y> [button]`, `mousemove` and `action <name> <down|up>`. Building ids are `admissions`, `dorm`, `engineering_1` and `dining_1`. Free ground on screen at the default camera is around (30, 15) and (40, 15).

**The start state:**
- 800 students (4 cohorts of 200 at 3.12) in 800 seats, 360 beds, and dining for 650
- reputation 61.5, $50M cash, no debt
- buildings, by index:
  - 0–2: dorms
  - 3–4: engineering
  - 5: dining
  - 6: admissions

---

### Task 1: State for the panes

**Files:**
- Modify:
  - `university/src/state/policy.gd`
  - `university/src/state/university.gd`
  - `university/src/state/campus.gd`
  - `university/src/data/building_info.gd`
  - `university/src/data/building_info_db.gd`
  - `university/src/ui/university_menu.gd`
  - `CLAUDE.md`
- Test:
  - `university/tests/PolicyTest.gd`
  - `university/tests/UniversityTest.gd`
  - `university/tests/CampusTest.gd`
  - `university/tests/BuildingInfoTest.gd`

**Interfaces:**
- **Produces:**
  - **`Policy`:**
    - `PriceStep: int` (100) and `GradeStep: float` (0.1)
    - `stepNextTuition(direction: int)`, `stepNextRoom(direction: int)`, `stepNextMealPlan(direction: int)`
    - `stepMinimum(direction: int)`: from off, a step up starts at `UniversityRules.GradeBase`; stepping below that turns it off
  - **`BuildingInfo`:**
    - `enum Role { Admissions, Academic, Housing, Dining, Other }`
    - `role() -> Role`: the first that applies, in that order
    - `capacity() -> int`: the seats, beds or meals of its role, or 0
  - **`BuildingInfoDB`:**
    - `categories() -> Array[String]`, in the order the sheet first uses them
    - `inCategory(category: String) -> Array[BuildingInfo]`
  - **`Campus`:**
    - `openWithRole(role: BuildingInfo.Role) -> Array[Building]`
    - `capacityFor(role: BuildingInfo.Role) -> int`
    - `refundFor(building: Building) -> int` (`destroy` uses it)
    - `static centroid(group: Array[Building]) -> Vector2`
  - **`University`:**
    - `offCampusWith(bedCount: int) -> int` and `offCampusShareWith(bedCount: int) -> float`; `offCampus()` and `offCampusShare()` delegate to them
    - `feesNow() -> Fees` (`_startSemester` uses it)
    - `roomFeesOf(building: Building) -> int`
    - `fallReports() -> Array[SemesterReport]`

- [ ] **Step 1: Write the failing tests** (12 new `test_` functions: Policy 3, University 4, Campus 3, BuildingInfo 2)

**`university/tests/PolicyTest.gd`**, append:

```gdscript


const GradeEpsilon: float = 0.0001


func test_price_steppers_move_next_years_prices_and_stop_at_zero() -> void:
	var policy: Policy = Policy.new()
	var tuition: int = policy.next.tuition
	var room: int = policy.next.room
	policy.stepNextTuition(1)
	policy.stepNextRoom(-1)
	assert_int(policy.next.tuition).is_equal(tuition + Policy.PriceStep)
	assert_int(policy.next.room).is_equal(room - Policy.PriceStep)
	policy.setNextMealPlan(0)
	policy.stepNextMealPlan(-1)
	assert_int(policy.next.mealPlan).is_equal(0)
	# Only next year moves; this year's prices are locked.
	assert_int(policy.current.total()).is_equal(Policy.defaultPrices().total())


func test_the_minimum_starts_at_the_base_cutoff_and_turns_off_below_it() -> void:
	var policy: Policy = Policy.new()
	policy.stepMinimum(-1)
	assert_float(policy.minimumGrade).is_equal(0.0)
	policy.stepMinimum(1)
	assert_float(policy.minimumGrade).is_equal_approx(UniversityRules.GradeBase, GradeEpsilon)
	policy.stepMinimum(1)
	assert_float(policy.minimumGrade).is_equal_approx(UniversityRules.GradeBase + Policy.GradeStep, GradeEpsilon)
	policy.stepMinimum(-1)
	policy.stepMinimum(-1)
	assert_float(policy.minimumGrade).is_equal(0.0)


func test_the_minimum_never_passes_the_top_grade() -> void:
	var policy: Policy = Policy.new()
	policy.setMinimumGrade(UniversityRules.MaxGrade)
	policy.stepMinimum(1)
	assert_float(policy.minimumGrade).is_equal_approx(UniversityRules.MaxGrade, GradeEpsilon)
```

**`university/tests/UniversityTest.gd`**, append. This reuses `_running()`, `_last()`, `_hall()`, `HallBeds`, `Grade`, `Diameter` and `Epsilon`.

```gdscript


func test_more_beds_move_students_back_on_campus() -> void:
	var university: University = _running()
	university.students.admit(HallBeds * 2, Grade)
	var beds: int = university.campus.beds()
	assert_int(university.offCampusWith(beds)).is_equal(university.offCampus())
	assert_int(university.offCampusWith(beds + HallBeds)).is_equal(maxi(university.offCampus() - HallBeds, 0))
	assert_float(university.offCampusShareWith(beds)).is_equal_approx(university.offCampusShare(), Epsilon)


func test_the_fees_now_are_what_the_last_semester_start_collected() -> void:
	# _running() stands just after a spring start: nothing has changed since.
	var university: University = _running()
	assert_int(university.feesNow().total()).is_equal(_last(university).totalFees())


func test_a_lone_dorms_room_fees_are_the_semesters() -> void:
	var university: University = _running()
	var hall: Building = university.campus.buildings[0]
	assert_int(university.roomFeesOf(hall)).is_equal(university.feesNow().room)


func test_fall_reports_are_the_fall_starts_oldest_first() -> void:
	var university: University = _running()
	assert_array(university.fallReports()).is_empty()
	university.startMonth(university.nextFallStart())
	var first: SemesterReport = _last(university)
	university.startMonth(university.nextSemesterStart())
	university.startMonth(university.nextFallStart())
	var falls: Array[SemesterReport] = university.fallReports()
	assert_int(falls.size()).is_equal(2)
	assert_object(falls[0]).is_same(first)
	assert_object(falls[1]).is_same(university.lastFallReport())
```

**`university/tests/CampusTest.gd`**, append. This reuses `_campus()`, `_info()`, `_priced()`, `Diameter` and `Beds`.

```gdscript


const CentroidEpsilon: float = 0.0001


func test_the_refund_is_the_cost_until_the_building_opens() -> void:
	var campus: Campus = _campus()
	var building: Building = campus.place(_priced(), Vector2.ZERO, 0.0)
	assert_int(campus.refundFor(building)).is_equal(building.info.cost)
	campus.startMonth(building.opensAtMonth)
	assert_int(campus.refundFor(building)).is_equal(0)


func test_the_centroid_is_the_middle_of_the_buildings() -> void:
	var campus: Campus = _campus()
	var left: Building = campus.place(_info(), Vector2(-Diameter * 2.0, 0.0), 0.0)
	var right: Building = campus.place(_info(), Vector2(Diameter * 2.0, Diameter * 2.0), 0.0)
	var pair: Array[Building] = [left, right]
	assert_vector(Campus.centroid(pair)).is_equal_approx((left.pos + right.pos) / 2.0, Vector2(CentroidEpsilon, CentroidEpsilon))
	var none: Array[Building] = []
	assert_vector(Campus.centroid(none)).is_equal(Vector2.ZERO)


func test_open_buildings_are_found_and_counted_by_role() -> void:
	var campus: Campus = _campus()
	var dorm: BuildingInfo = BuildingInfo.new({"id": "dorm", "name": "Dorm", "diameter": Diameter, "beds": Beds})
	var open: Building = campus.place(dorm, Vector2.ZERO, 0.0)
	campus.startMonth(open.opensAtMonth)
	campus.place(dorm, Vector2(Diameter * 2.0, 0.0), 0.0)
	assert_array(campus.openWithRole(BuildingInfo.Role.Housing)).contains_exactly([open])
	assert_array(campus.openWithRole(BuildingInfo.Role.Dining)).is_empty()
	assert_int(campus.capacityFor(BuildingInfo.Role.Housing)).is_equal(campus.beds())
```

**`university/tests/BuildingInfoTest.gd`**, append:

```gdscript


const FixtureDiameter: float = 10.0
const FixtureCapacity: int = 10


func test_a_type_counts_as_its_first_role_and_holds_that_capacity() -> void:
	var both: BuildingInfo = BuildingInfo.new({"id": "both", "name": "Both", "seats": FixtureCapacity, "beds": FixtureCapacity * 2})
	assert_int(both.role()).is_equal(BuildingInfo.Role.Academic)
	assert_int(both.capacity()).is_equal(both.seats)
	var office: BuildingInfo = BuildingInfo.new({"id": "office", "name": "Office", "seats": FixtureCapacity, "admissionsOffice": true})
	assert_int(office.role()).is_equal(BuildingInfo.Role.Admissions)
	assert_int(office.capacity()).is_equal(0)
	assert_int(BuildingInfo.new({"id": "bare", "name": "Bare"}).role()).is_equal(BuildingInfo.Role.Other)


func test_categories_keep_the_order_the_sheet_first_uses_them() -> void:
	var records: Array[Dictionary] = [
		{"id": "a", "name": "A", "category": "Second", "diameter": FixtureDiameter},
		{"id": "b", "name": "B", "category": "First", "diameter": FixtureDiameter},
		{"id": "c", "name": "C", "category": "Second", "diameter": FixtureDiameter},
	]
	var db: BuildingInfoDB = BuildingInfoDB.new(records)
	assert_array(db.categories()).contains_exactly(["Second", "First"])
	assert_int(db.inCategory("Second").size()).is_equal(2)
	assert_object(db.inCategory("Second")[0]).is_same(db.info("a"))
```

- [ ] **Step 2: Run the tests and watch them fail**

Run RUN-TESTS. The four suites drop out with parse errors, because the new methods don't exist yet.

- [ ] **Step 3: `Policy` steppers**

In `university/src/state/policy.gd`, below the default-price consts, add:

```gdscript
# The Admissions Office steppers' increments: prices move PriceStep dollars at a
# time, the minimum GradeStep of a grade.
const PriceStep: int = 100
const GradeStep: float = 0.1
# Half a step: how close to GradeBase still counts as at it, against float drift.
const GradeSlack: float = GradeStep / 2.0
```

After `setMinimumGrade`, add:

```gdscript
## Moves next year's tuition a step: up for direction 1, down for -1.
func stepNextTuition(direction: int) -> void:
	setNextTuition(next.tuition + direction * PriceStep)


func stepNextRoom(direction: int) -> void:
	setNextRoom(next.room + direction * PriceStep)


func stepNextMealPlan(direction: int) -> void:
	setNextMealPlan(next.mealPlan + direction * PriceStep)


## Moves the minimum grade a step. From off, a step up starts it at
## UniversityRules.GradeBase, the cutoff when applicants equal seats; a step
## below that turns it off again, since a minimum under the cutoff trims nobody.
func stepMinimum(direction: int) -> void:
	if (minimumGrade <= 0.0):
		if (direction > 0):
			setMinimumGrade(UniversityRules.GradeBase)
		return
	var stepped: float = roundf((minimumGrade + float(direction) * GradeStep) / GradeStep) * GradeStep
	setMinimumGrade(stepped if (stepped >= UniversityRules.GradeBase - GradeSlack) else 0.0)
```

- [ ] **Step 4: Roles and categories**

In `university/src/data/building_info.gd`, after the consts, add:

```gdscript
## What a type is for, which decides its side-panel pane and how it is counted.
## A type with several capacities is the first that applies, in this order.
enum Role { Admissions, Academic, Housing, Dining, Other }
```

After `_init`, add:

```gdscript
func role() -> Role:
	if (admissionsOffice):
		return Role.Admissions
	if (seats > 0):
		return Role.Academic
	if (beds > 0):
		return Role.Housing
	if (meals > 0):
		return Role.Dining
	return Role.Other


## What this type holds of its role: seats, beds or meals; 0 for the others.
func capacity() -> int:
	match role():
		Role.Academic:
			return seats
		Role.Housing:
			return beds
		Role.Dining:
			return meals
	return 0
```

In `university/src/data/building_info_db.gd`, after `info`, add:

```gdscript
## The categories in the order the sheet first uses them: the build panel's tabs.
func categories() -> Array[String]:
	var found: Array[String] = []
	for buildingInfo: BuildingInfo in all:
		if (not found.has(buildingInfo.category)):
			found.append(buildingInfo.category)
	return found


## The types in one category, in sheet order.
func inCategory(category: String) -> Array[BuildingInfo]:
	var found: Array[BuildingInfo] = []
	for buildingInfo: BuildingInfo in all:
		if (buildingInfo.category == category):
			found.append(buildingInfo)
	return found
```

- [ ] **Step 5: `Campus`: roles, the refund and the centroid**

In `university/src/state/campus.gd`, replace these lines in `destroy`:

```gdscript
	if (building.underConstruction):
		finances.refund(building.info.cost)
```

with:

```gdscript
	var refunded: int = refundFor(building)
	if (refunded > 0):
		finances.refund(refunded)
```

After `openBuildings()`, add:

```gdscript
## The open buildings of one role, in placement order.
func openWithRole(role: BuildingInfo.Role) -> Array[Building]:
	var found: Array[Building] = []
	for building: Building in openBuildings():
		if (building.info.role() == role):
			found.append(building)
	return found


## What the open buildings hold of one role: seats, beds or meals.
func capacityFor(role: BuildingInfo.Role) -> int:
	match role:
		BuildingInfo.Role.Academic:
			return seats()
		BuildingInfo.Role.Housing:
			return beds()
		BuildingInfo.Role.Dining:
			return meals()
	return 0


## What destroying a building gives back: its full cost while it is still under
## construction, nothing once it has opened. The one rule destroy and the
## Demolish button both read.
func refundFor(building: Building) -> int:
	return building.info.cost if (building.underConstruction) else 0


## The middle of some buildings on the ground, where a marker about them
## stands; the origin for none.
static func centroid(group: Array[Building]) -> Vector2:
	if (group.is_empty()):
		return Vector2.ZERO
	var sum: Vector2 = Vector2.ZERO
	for building: Building in group:
		sum += building.pos
	return sum / float(group.size())
```

- [ ] **Step 6: `University`: counterfactual off campus, the fees now, fall reports**

In `university/src/state/university.gd`, replace `offCampus()` and `offCampusShare()` (keeping their doc comments) with:

```gdscript
## Enrolled students without a bed on campus.
func offCampus() -> int:
	return offCampusWith(campus.beds())


## Students who would live off campus with that many beds, at today's
## enrolment: what a dorm opening would change.
func offCampusWith(bedCount: int) -> int:
	return students.enrolled() - UniversityRules.housed(students.enrolled(), bedCount)
```

and:

```gdscript
## The fraction of enrolled students living off campus.
func offCampusShare() -> float:
	return offCampusShareWith(campus.beds())


func offCampusShareWith(bedCount: int) -> float:
	return UniversityRules.offCampusShare(students.enrolled(), UniversityRules.housed(students.enrolled(), bedCount))
```

After `projectedFees()`, add:

```gdscript
## This semester's fees at today's numbers and this year's prices: what a
## semester start collects.
func feesNow() -> Fees:
	return UniversityRules.fees(policy.current, students.enrolled(), housed(), mealPlans())


## One dorm's room fees a semester: its residents at this year's room price.
func roomFeesOf(building: Building) -> int:
	return residentsOf(building) * policy.current.room
```

After `lastFallReport()`, add:

```gdscript
## Every fall start's report, oldest first: the applicants-per-fall chart.
func fallReports() -> Array[SemesterReport]:
	var falls: Array[SemesterReport] = []
	for report: SemesterReport in reports:
		if (report.isFall):
			falls.append(report)
	return falls
```

In `_startSemester`, replace:

```gdscript
	var fees: Fees = UniversityRules.fees(policy.current, students.enrolled(), housed(), mealPlans())
```

with:

```gdscript
	var fees: Fees = feesNow()
```

- [ ] **Step 7: The University menu counts by role**

In `university/src/ui/university_menu.gd`:
- Delete `_count` and `_chooseFirst`.
- Count with `university.campus.openWithRole(BuildingInfo.Role.Housing).size()` and `openWithRole(BuildingInfo.Role.Dining).size()`.
- For Admissions and Dining, emit `BuildingChosen` with the first building of `openWithRole(BuildingInfo.Role.Admissions)` or `openWithRole(BuildingInfo.Role.Dining)`, when there is one.
- Keep everything else as it is.

- [ ] **Step 8: Run the tests**

Run RUN-TESTS. Expected: 222 cases (210 + 12) in 20 suites.

- [ ] **Step 9: Update `CLAUDE.md`**

In the student-loop projections list, add:
- `offCampusWith` / `offCampusShareWith(beds)`: what opening beds would change
- `feesNow()`: what a semester start collects; `_startSemester` uses it
- `roomFeesOf(building)`
- `fallReports()`

In the Architecture's Campus sentence, add:
- `refundFor(building)`: the one refund rule, which `destroy` reads
- `openWithRole(role)` and `capacityFor(role)`
- `Campus.centroid(buildings)`

In the Data section, add:
- `BuildingInfo.role()`, the first of Admissions, Academic, Housing and Dining that applies, and `capacity()`
- `BuildingInfoDB.categories()` in first-appearance order, and `inCategory`

Mention the `Policy` steppers: `PriceStep`, `GradeStep`, `stepNext*` and `stepMinimum`, where off steps up to `GradeBase`.

- [ ] **Step 10: LAUNCH-CHECK, then commit**

Run LAUNCH-CHECK with `pause`, `hud unimenu` and `screenshot`. The University menu still shows "3 dorms" and "1 hall".

```bash
cd /Users/noel/Development/University/game
git add university/src/state/policy.gd university/src/state/university.gd university/src/state/campus.gd university/src/data/building_info.gd university/src/data/building_info_db.gd university/src/ui/university_menu.gd university/tests/PolicyTest.gd university/tests/UniversityTest.gd university/tests/CampusTest.gd university/tests/BuildingInfoTest.gd CLAUDE.md
git commit -m "$(cat <<'EOF'
Answer the panes from state: roles, steppers, refunds, what opening changes

Co-Authored-By: Claude <the model you actually are> <noreply@anthropic.com>
EOF
)"
```

---

### Task 2: Wording, the alert feed, the stepper and the dining load line

**Files:**
- Create:
  - `university/src/ui/building_text.gd`
  - `university/src/ui/alert_entry.gd`
  - `university/src/ui/alert_feed.gd`
  - `university/src/ui/stepper.tscn` and `university/src/ui/stepper.gd`
  - `university/src/ui/dining_load_line.tscn` and `university/src/ui/dining_load_line.gd`
- Modify:
  - `university/src/ui/housing_dropdown.tscn` and `university/src/ui/housing_dropdown.gd` (these use `DiningLoadLine`)
  - `university/src/ui/ui_theme.tres`
- Test: `university/tests/BuildingTextTest.gd` and `university/tests/AlertFeedTest.gd` (both new)

**Interfaces:**
- **Produces:**
  - **`BuildingText`:**
    - `holds(info) -> String` ("400 seats", "120 beds", "recommended for 650", "Admission and prices", "")
    - `adds(info) -> String` ("+400 seats", "+120 beds", "+650 diners", "")
    - `footprint(info) -> String` ("40 × 24 m")
  - **`AlertEntry`:**
    - `enum Source { Problem, AutoBorrowed, Opened }`
    - fields: `source`, `problem`, `amount`, `fee`, `building`, `week`
    - `_init(entrySource: Source, atWeek: int)`
  - **`AlertFeed`:**
    - `MaxEvents: int` (5)
    - `update(current: Array[Problem], week: int)`
    - `addEvent(entry)`, `dismiss(entry)`
    - `shown() -> Array[AlertEntry]`
  - **`Stepper`** (HBoxContainer): `signal Stepped(direction: int)` and `display(caption: String, value: String, dimmed: bool)`
  - **`DiningLoadLine`** (HBoxContainer): `display(university: University)` and `static toneFor(university: University) -> UiTone.Tone`
  - **Theme variations:** `StepCaption`, `StepButton`, `StepBox`, `StepValue`, `StepValueDim`

- [ ] **Step 1: Write the failing tests** (6 new `test_` functions in 2 new suites)

Create `university/tests/BuildingTextTest.gd`:

```gdscript
extends GdUnitTestSuite
## How building types are worded. Fixtures are arbitrary.

const Diameter: float = 40.0
const Seats: int = 400


func test_a_type_holds_and_adds_its_capacity() -> void:
	var hall: BuildingInfo = BuildingInfo.new({"id": "hall", "name": "Hall", "diameter": Diameter, "seats": Seats})
	assert_str(BuildingText.holds(hall)).contains(NumberFormat.count(Seats))
	assert_str(BuildingText.adds(hall)).starts_with("+")
	assert_str(BuildingText.adds(hall)).contains(NumberFormat.count(Seats))
	var bare: BuildingInfo = BuildingInfo.new({"id": "bare", "name": "Bare", "diameter": Diameter})
	assert_str(BuildingText.adds(bare)).is_empty()


func test_the_footprint_is_the_placed_box() -> void:
	var hall: BuildingInfo = BuildingInfo.new({"id": "hall", "name": "Hall", "diameter": Diameter})
	var box: Vector2 = Building.rectFor(hall, Vector2.ZERO, 0.0).size
	assert_str(BuildingText.footprint(hall)).is_equal(BuildingText.FootprintFormat % [roundi(box.x), roundi(box.y)])
```

Create `university/tests/AlertFeedTest.gd`:

```gdscript
extends GdUnitTestSuite
## The alerts list's rules. Problems and events are arbitrary fixtures.

const FirstWeek: int = 3
const LaterWeek: int = 7
const Count: int = 10
const Share: float = 0.5


func _overflow() -> Array[Problem]:
	var problems: Array[Problem] = [Problem.new(Problem.Kind.HousingOverflow, Count, Share)]
	return problems


func _none() -> Array[Problem]:
	var problems: Array[Problem] = []
	return problems


func test_a_problem_shows_while_it_holds_dated_when_it_appeared() -> void:
	var feed: AlertFeed = AlertFeed.new()
	feed.update(_overflow(), FirstWeek)
	feed.update(_overflow(), LaterWeek)
	assert_int(feed.shown().size()).is_equal(1)
	assert_int(feed.shown()[0].week).is_equal(FirstWeek)
	feed.update(_none(), LaterWeek)
	assert_array(feed.shown()).is_empty()


func test_a_dismissed_problem_stays_hidden_until_it_clears() -> void:
	var feed: AlertFeed = AlertFeed.new()
	feed.update(_overflow(), FirstWeek)
	feed.dismiss(feed.shown()[0])
	feed.update(_overflow(), LaterWeek)
	assert_array(feed.shown()).is_empty()
	feed.update(_none(), LaterWeek)
	feed.update(_overflow(), LaterWeek)
	assert_int(feed.shown().size()).is_equal(1)
	assert_int(feed.shown()[0].week).is_equal(LaterWeek)


func test_events_show_newest_first_and_the_oldest_drop_off() -> void:
	var feed: AlertFeed = AlertFeed.new()
	for week: int in range(AlertFeed.MaxEvents + 1):
		feed.addEvent(AlertEntry.new(AlertEntry.Source.AutoBorrowed, week))
	var lines: Array[AlertEntry] = feed.shown()
	assert_int(lines.size()).is_equal(AlertFeed.MaxEvents)
	assert_int(lines[0].week).is_equal(AlertFeed.MaxEvents)
	assert_int(lines[lines.size() - 1].week).is_equal(1)


func test_problems_come_first_and_a_dismissed_event_is_gone() -> void:
	var feed: AlertFeed = AlertFeed.new()
	var event: AlertEntry = AlertEntry.new(AlertEntry.Source.AutoBorrowed, FirstWeek)
	feed.addEvent(event)
	feed.update(_overflow(), LaterWeek)
	assert_int(feed.shown()[0].source).is_equal(AlertEntry.Source.Problem)
	feed.dismiss(event)
	assert_int(feed.shown().size()).is_equal(1)
	assert_int(feed.shown()[0].source).is_equal(AlertEntry.Source.Problem)
```

- [ ] **Step 2: Run the tests and watch them fail**

Run RUN-TESTS. Both new suites fail to parse.

- [ ] **Step 3: `BuildingText`**

Create `university/src/ui/building_text.gd`:

```gdscript
class_name BuildingText
## How a building type reads: what it holds ("400 seats"), what building one
## adds ("+400 seats") and its footprint ("40 × 24 m"). The one place these are
## worded, for the side panel, the build cards and the campus markers.

const HoldsSeats: String = "%s seats"
const HoldsBeds: String = "%s beds"
const HoldsMeals: String = "recommended for %s"
const HoldsAdmissions: String = "Admission and prices"
const AddsSeats: String = "+%s seats"
const AddsBeds: String = "+%s beds"
const AddsMeals: String = "+%s diners"
const FootprintFormat: String = "%d × %d m"


static func holds(info: BuildingInfo) -> String:
	match info.role():
		BuildingInfo.Role.Academic:
			return HoldsSeats % NumberFormat.count(info.capacity())
		BuildingInfo.Role.Housing:
			return HoldsBeds % NumberFormat.count(info.capacity())
		BuildingInfo.Role.Dining:
			return HoldsMeals % NumberFormat.count(info.capacity())
		BuildingInfo.Role.Admissions:
			return HoldsAdmissions
	return ""


## What building one of these adds; empty for a type that adds no capacity.
static func adds(info: BuildingInfo) -> String:
	match info.role():
		BuildingInfo.Role.Academic:
			return AddsSeats % NumberFormat.count(info.capacity())
		BuildingInfo.Role.Housing:
			return AddsBeds % NumberFormat.count(info.capacity())
		BuildingInfo.Role.Dining:
			return AddsMeals % NumberFormat.count(info.capacity())
	return ""


## The footprint, long side by short, in whole metres: the box Building.rectFor places.
static func footprint(info: BuildingInfo) -> String:
	var box: Vector2 = Building.rectFor(info, Vector2.ZERO, 0.0).size
	return FootprintFormat % [roundi(box.x), roundi(box.y)]
```

- [ ] **Step 4: `AlertEntry` and `AlertFeed`**

Create `university/src/ui/alert_entry.gd`:

```gdscript
class_name AlertEntry
## One line in the alerts list: a problem that holds now, or an event.

enum Source { Problem, AutoBorrowed, Opened }

var source: Source
# The problem, for Source.Problem; refreshed every update while it holds.
var problem: Problem
# The shortfall and its fee, for Source.AutoBorrowed.
var amount: int = 0
var fee: int = 0
# The building that opened, for Source.Opened.
var building: Building
# Weeks since the game began, when it first showed.
var week: int = 0


func _init(entrySource: Source, atWeek: int) -> void:
	source = entrySource
	week = atWeek
```

Create `university/src/ui/alert_feed.gd`:

```gdscript
class_name AlertFeed
## Which alerts show. Plain data, so its rules are tested without the engine:
## - a problem shows while it holds, dated the week it first appeared;
## - dismissing a problem hides it until it clears, and it comes back, newly
##   dated, if it returns;
## - events show newest first, at most MaxEvents, until dismissed;
## - problems come before events.

const MaxEvents: int = 5

var _problems: Array[AlertEntry] = []
var _events: Array[AlertEntry] = []
# Problem kinds dismissed while they still hold; each is forgotten when its
# problem clears.
var _dismissed: Array[int] = []


## Brings the problem lines up to date with what is wrong now.
func update(current: Array[Problem], week: int) -> void:
	var kept: Array[AlertEntry] = []
	var present: Array[int] = []
	for problem: Problem in current:
		present.append(problem.kind)
		var entry: AlertEntry = _problemEntry(problem.kind)
		if (entry == null):
			entry = AlertEntry.new(AlertEntry.Source.Problem, week)
		entry.problem = problem
		kept.append(entry)
	_problems = kept
	var stillDismissed: Array[int] = []
	for kind: int in _dismissed:
		if (present.has(kind)):
			stillDismissed.append(kind)
	_dismissed = stillDismissed


## A new event, shown first; the oldest beyond MaxEvents drops off.
func addEvent(entry: AlertEntry) -> void:
	_events.push_front(entry)
	if (_events.size() > MaxEvents):
		_events.resize(MaxEvents)


func dismiss(entry: AlertEntry) -> void:
	if (entry.source == AlertEntry.Source.Problem):
		if (not _dismissed.has(entry.problem.kind)):
			_dismissed.append(entry.problem.kind)
	else:
		_events.erase(entry)


## What shows now: the problems not dismissed, in problems() order, then the
## events, newest first.
func shown() -> Array[AlertEntry]:
	var lines: Array[AlertEntry] = []
	for entry: AlertEntry in _problems:
		if (not _dismissed.has(entry.problem.kind)):
			lines.append(entry)
	lines.append_array(_events)
	return lines


func _problemEntry(kind: Problem.Kind) -> AlertEntry:
	for entry: AlertEntry in _problems:
		if (entry.problem.kind == kind):
			return entry
	return null
```

- [ ] **Step 5: REGISTER, then RUN-TESTS**

Expected: 228 cases (222 + 6) in 22 suites.

- [ ] **Step 6: `Stepper`**

Add these variations to `ui_theme.tres`, following the mockup's `.inp`:

| Variation | Base | Font / size | Colour | Style |
|---|---|---|---|---|
| `StepCaption` | Label | BarlowSemiCondensed-Medium 11 | muted | none |
| `StepButton` | Button | Barlow-Medium 16 | muted, with hover font text | normal: chrome with a 1 px line2 border, radius 4, margins 0. Hover and pressed: the same with a gold border. Focus: StyleBoxEmpty. |
| `StepBox` | PanelContainer | none | none | panel: chrome with a 1 px line2 border, radius 4, content margins 10 left and right, 0 top and bottom |
| `StepValue` | Label | Barlow-SemiBold 14 | text | none |
| `StepValueDim` | Label | Barlow-Medium 14 | dim | none |

`university/src/ui/stepper.tscn` has root `Stepper` (HBoxContainer, separation 8, script `stepper.gd`). Its children:
- `Caption`: Label, unique, `StepCaption`, `uppercase`, `custom_minimum_size.x = 92`, vertically centred
- `Down`: Button, unique, `StepButton`, text "−", 30×30, `focus_mode = 0`
- `Box`: PanelContainer, `StepBox`, `size_flags_horizontal = 3`, `custom_minimum_size.y = 30`. It holds `Value` (Label, unique, `StepValue`, vertically centred).
- `Up`: Button, unique, `StepButton`, text "+", 30×30, `focus_mode = 0`

`university/src/ui/stepper.gd`:

```gdscript
class_name Stepper
extends HBoxContainer
## A labelled value with − and + beside it: an Admissions Office lever. It only
## announces a step; the owner of the value applies it and shows the result.

signal Stepped(direction: int)

const ValueBase: String = "StepValue"

@onready var captionLabel: Label = %Caption
@onready var downButton: Button = %Down
@onready var upButton: Button = %Up
@onready var valueLabel: Label = %Value


func _ready() -> void:
	downButton.pressed.connect(func() -> void: Stepped.emit(-1))
	upButton.pressed.connect(func() -> void: Stepped.emit(1))


func display(caption: String, value: String, dimmed: bool) -> void:
	captionLabel.text = caption
	valueLabel.text = value
	valueLabel.theme_type_variation = UiTone.variation(ValueBase, UiTone.Tone.Dim if (dimmed) else UiTone.Tone.Normal)
```

`StepValue` is toned only Normal or Dim, and both variants exist.

- [ ] **Step 7: `DiningLoadLine`, and the Housing dropdown uses it**

`university/src/ui/dining_load_line.tscn` has root `DiningLoadLine` (HBoxContainer, separation 10, script `dining_load_line.gd`). Its children:
- `Bar`: a Control with the MeterBar script, unique, 150×8, `size_flags_vertical = 4`
- `Value`: Label, unique, `RowValue`

`university/src/ui/dining_load_line.gd`:

```gdscript
class_name DiningLoadLine
extends HBoxContainer
## The dining load as a bar and a percentage: the fill ends at the hard limit,
## the mark is the recommended load, and the tone says crowded or can't eat.
## The Housing dropdown and the dining hall's pane both show it.

const LoadNormal: String = "%s"
const LoadCrowded: String = "%s · crowded"
const LoadUnfed: String = "%s · can't eat"
# The red limit sits at the bar's end: the fill is scaled to the hard limit.
const LimitAtEnd: float = 1.0

@onready var bar: MeterBar = %Bar
@onready var valueLabel: Label = %Value


## The one tone the dining load reads in, from University.problems().
static func toneFor(university: University) -> UiTone.Tone:
	if (university.hasProblem(Problem.Kind.DiningUnfed)):
		return UiTone.Tone.Bad
	if (university.hasProblem(Problem.Kind.DiningCrowded)):
		return UiTone.Tone.Warn
	return UiTone.Tone.Normal


func display(university: University) -> void:
	var tone: UiTone.Tone = toneFor(university)
	var diningLoad: float = university.diningLoad()
	var marks: Array[float] = [UniversityRules.RecommendedLoad / UniversityRules.DiningHardLimit]
	bar.setValue(diningLoad / UniversityRules.DiningHardLimit, tone, marks, LimitAtEnd)
	var valueFormat: String = LoadNormal
	if (tone == UiTone.Tone.Bad):
		valueFormat = LoadUnfed
	elif (tone == UiTone.Tone.Warn):
		valueFormat = LoadCrowded
	valueLabel.text = valueFormat % NumberFormat.percent(diningLoad)
	valueLabel.theme_type_variation = UiTone.variation(InfoRow.ValueBase, tone)
```

In the Housing dropdown:
- In `housing_dropdown.tscn`, replace `LoadBar` and `LoadValue` inside `LoadLine` with a `DiningLoadLine` instance (unique `DiningLoadLine`). Keep the "Load" key label.
- In `housing_dropdown.gd`, add `@onready var diningLoadLine: DiningLoadLine = %DiningLoadLine`, and replace the tone, bar and value code in `_showDining` with `diningLoadLine.display(university)`. Then delete the consts and `@onready` vars that are no longer used (`LoadNormal`, `LoadCrowded`, `LoadUnfed`, `loadBar`, `loadValue`, and any others).
- `DinersRow`, the no-dining note and the rest stay as they are.

- [ ] **Step 8: REGISTER, RUN-TESTS, LAUNCH-CHECK, commit**

Run REGISTER, then RUN-TESTS (228 in 22). Then LAUNCH-CHECK: `pause`, `hud housing`, `screenshot`. The dining block looks exactly as it did: the bar about 43% filled with the mark at 77%, and "55%".

```bash
git add university/src/ui/building_text.gd university/src/ui/building_text.gd.uid university/src/ui/alert_entry.gd university/src/ui/alert_entry.gd.uid university/src/ui/alert_feed.gd university/src/ui/alert_feed.gd.uid university/src/ui/stepper.tscn university/src/ui/stepper.gd university/src/ui/stepper.gd.uid university/src/ui/dining_load_line.tscn university/src/ui/dining_load_line.gd university/src/ui/dining_load_line.gd.uid university/src/ui/housing_dropdown.tscn university/src/ui/housing_dropdown.gd university/src/ui/ui_theme.tres university/tests/BuildingTextTest.gd university/tests/BuildingTextTest.gd.uid university/tests/AlertFeedTest.gd university/tests/AlertFeedTest.gd.uid
git commit -m "$(cat <<'EOF'
Word building types, feed the alerts, and add the stepper and dining load line

Co-Authored-By: Claude <the model you actually are> <noreply@anthropic.com>
EOF
)"
```

---

### Task 3: The `SidePanel` and the construction pane, replacing `InfoPanel`

**Files:**
- Create:
  - `university/src/ui/side_panel.tscn` and `university/src/ui/side_panel.gd`
  - `university/src/ui/construction_pane.tscn` and `university/src/ui/construction_pane.gd`
- Modify:
  - `university/src/ui/hud.tscn` and `university/src/ui/hud.gd`
  - `university/src/views/campus_view.tscn` and `university/src/views/campus_view.gd`
  - `university/src/debug/debug_commands.gd`
  - `university/src/ui/ui_theme.tres`
  - `CLAUDE.md`
- Delete: `university/src/ui/info_panel.tscn`, and `university/src/ui/info_panel.gd` with its `.uid`

**Interfaces:**
- **Produces:**
  - **`SidePanel`** (PanelContainer):
    - signals: `CloseRequested`, `PopoverWanted(which: StringName)`, `BuildWanted(category: String)`, `BuildingWanted(building: Building)`
    - `setUniversity(shown: University)`
    - `showBuilding(selected: Building)`: null closes it
    - `building: Building`
  - **The pane pattern** (every pane follows it):
    - a script extending VBoxContainer with `var university: University` and `var building: Building`
    - it fills itself in `_process` while visible
    - it emits `PopoverWanted`, `BuildWanted` or `BuildingWanted` for its jumps
    - `SidePanel` relays those signals
  - **`ConstructionPane`**: shows what opening changes, and the refund
  - **`Hud`:**
    - `showPane(which: StringName)`, which selects the first building for a pane name and moves the camera to it. The names are `&"construction"`, the first building under construction; Task 4 and Task 5 add `admissions`, `academic`, `dorm` and `dining`.
    - `showBuilding(building: Building)`, which selects it and moves the camera there. It is today's `_showBuilding`, now public.
  - **The console:** `hud construction`

**How it behaves:**
- The panel opens on selection and closes with it: `BuildController.SelectionChanged`.
- × clears the selection.
- A left click on empty ground clears it too, as today.
- The panel is docked right, 420 px wide, from under the top bar down to the bottom of the screen.
- It isn't a popover: a dropdown can be open beside it, and Esc clears it only at the "selection" step.
- The header reads:
  - the type's name, as the title
  - "Category · what it holds", as the subtitle (`BuildingText.holds`)
  - an info pill, "Under construction · opens Spring, Year N", while it's going up
- The footer's Demolish button destroys the selected building. It reads "Demolish · refund $2.0M" while `Campus.refundFor` is above 0, and "Demolish" otherwise.
- The pane:
  - While the building is under construction, `ConstructionPane` shows.
  - Otherwise the role's pane shows (Tasks 4–5).
  - For now, an open building shows only the header and Demolish.

- [ ] **Step 1: Theme**

Add to `ui_theme.tres`:

| Variation | Base | Font / size | Colour | Style |
|---|---|---|---|---|
| `SidePanel` | PanelContainer | none | none | panel: chrome, a 1 px line2 border on the left only, shadow 30 at alpha 0.35, content margins 0 |
| `PaneHeader` | PanelContainer | none | none | panel: StyleBoxFlat with a transparent background, a 1 px line2 border on the bottom only, content margins 18 left and right, 16 top, 12 bottom |
| `PaneTitle` | Label | BarlowSemiCondensed-Bold 20 | text | none |
| `PaneSub` | Label | BarlowSemiCondensed-Medium 12 | muted | none |
| `CloseButton` | Button | Barlow-Regular 20 | muted, with hover font text | normal, hover, pressed and focus: StyleBoxEmpty with 4 px margins |

`PillInfo` doesn't exist yet: the pill variations are `Pill` (the info colour), `PillGood`, `PillWarn`, `PillBad` and `PillDim`. Use `Pill` for the info pill.

- [ ] **Step 2: `SidePanel` scene**

`university/src/ui/side_panel.tscn` has root `SidePanel`:
- PanelContainer, `SidePanel`, hidden, script `side_panel.gd`
- anchors left 1, right 1, top 0, bottom 1; offsets left −420, top 58, right 0, bottom 0
- default mouse_filter (STOP), so clicks on it never reach the world

Its child is `Layout` (VBoxContainer, separation 0), which holds:
1. `Header`: PanelContainer, `PaneHeader`. It holds an HBoxContainer (separation 12) of:
   - `Titles`: VBoxContainer, separation 5, size flags 3, holding `Title` (Label, unique, `PaneTitle`), `Sub` (Label, unique, `PaneSub`, `uppercase`), and `StatusPill` (Label, unique, `Pill`, hidden, `size_flags_horizontal = 0`)
   - `CloseButton`: Button, unique, `CloseButton`, text "×", `focus_mode = 0`, `size_flags_vertical = 0`
2. `Scroll`: ScrollContainer, `size_flags_vertical = 3`, `horizontal_scroll_mode = 0` (disabled). It holds `Body` (MarginContainer, margins 18/14/18/14, `size_flags_horizontal = 3`), which holds `Panes` (VBoxContainer, unique, `size_flags_horizontal = 3`). `Panes` holds `ConstructionPane` (a `construction_pane.tscn` instance, unique, hidden).
3. `Footer`: MarginContainer, margins 18/10/18/16. It holds an HBoxContainer holding `DemolishButton` (Button, unique, `GhostButton`, `focus_mode = 0`).

- [ ] **Step 3: `SidePanel` script**

`university/src/ui/side_panel.gd`:

```gdscript
class_name SidePanel
extends PanelContainer
## The docked panel on the right: the selected building. It opens on selection
## and closes with it. Its pane follows the building's role, or its
## construction while it is still going up. Demolish destroys the building
## under Campus.destroy's refund rule. It owns no state: everything is re-read
## each frame, so a building opening mid-view swaps its pane by itself.

signal CloseRequested
signal PopoverWanted(which: StringName)
signal BuildWanted(category: String)
signal BuildingWanted(building: Building)

const SubFormat: String = "%s · %s"
const OpensFormat: String = "Under construction · opens %s"
const DemolishText: String = "Demolish"
const DemolishRefundFormat: String = "Demolish · refund %s"

@onready var titleLabel: Label = %Title
@onready var subLabel: Label = %Sub
@onready var statusPill: Label = %StatusPill
@onready var closeButton: Button = %CloseButton
@onready var demolishButton: Button = %DemolishButton
@onready var constructionPane: ConstructionPane = %ConstructionPane

var university: University
var building: Building


func _ready() -> void:
	closeButton.pressed.connect(func() -> void: CloseRequested.emit())
	demolishButton.pressed.connect(_demolish)
	constructionPane.PopoverWanted.connect(func(which: StringName) -> void: PopoverWanted.emit(which))


func setUniversity(shown: University) -> void:
	university = shown
	constructionPane.university = shown


## The selected building, or null to close.
func showBuilding(selected: Building) -> void:
	building = selected
	visible = (building != null)


func _process(_dt: float) -> void:
	if (university == null or building == null):
		return
	var info: BuildingInfo = building.info
	titleLabel.text = info.name
	var holds: String = BuildingText.holds(info)
	subLabel.text = (SubFormat % [info.category, holds]) if (holds != "") else info.category
	statusPill.visible = building.underConstruction
	statusPill.text = OpensFormat % GameCalendar.periodLabel(building.opensAtMonth)
	var refund: int = university.campus.refundFor(building)
	demolishButton.text = (DemolishRefundFormat % MoneyFormat.short(refund)) if (refund > 0) else DemolishText
	_showPane(_paneFor(building))


# Which pane shows: construction while it is going up, else its role's pane.
# Roles without a pane show the header and Demolish only.
func _paneFor(shown: Building) -> Control:
	if (shown.underConstruction):
		return constructionPane
	return null


func _showPane(pane: Control) -> void:
	constructionPane.visible = (pane == constructionPane)
	constructionPane.building = building


func _demolish() -> void:
	# The controller hears BuildingRemoved and clears the selection, which
	# closes this panel.
	university.campus.destroy(building)
```

`BuildController._onBuildingRemoved` clears `selected` when the destroyed building was selected (checked by the controller), so Demolish closes the panel with no extra wiring.

- [ ] **Step 4: `ConstructionPane`**

`university/src/ui/construction_pane.tscn` has root `ConstructionPane` (VBoxContainer, separation 10, script `construction_pane.gd`). Its children:
- `OpensTitle`: Label, `SectionTitle`, `uppercase`, text "When it opens"
- `CapacityRow`: `info_row.tscn`, unique
- `OffCampusRow`: `info_row.tscn`, unique
- `UpkeepRow`: `info_row.tscn`, unique
- `RefundNote`: Label, unique, `Note`, autowrap
- `Jump`: Button, unique, `JumpButton`, `focus_mode = 0`

Mockup `#pane-uc` rows:
- **Capacity.** Key: the role's noun, "Beds", "Seats" or "Diners". Value: "+N", from `info.capacity()`. Note: "before → after", from `university.campus.capacityFor(role)` and that plus `info.capacity()`. Hidden when `info.capacity()` is 0.
- **Off campus.** Housing role only. Key "Off campus". Value: "before → after", from `university.offCampus()` and `university.offCampusWith(campus.beds() + info.beds)`. Note: "P% → Q%, under the threshold" or "P% → Q%, still above the threshold", from `offCampusShare()` and `offCampusShareWith(...)` against `UniversityRules.OverflowThreshold`.
- **Upkeep.** Key "Upkeep". Value: `MoneyFormat.signed(-info.upkeep) + " / mo"`, Bad. Note "from then on".
- **Refund note.** "Demolishing it before it opens refunds the full $X. Once it has opened, nothing comes back.", with `MoneyFormat.short(university.campus.refundFor(building))`.
- **Jump.** Housing and Dining roles: "All housing →", which emits `PopoverWanted(&"housing")`. Academic role: "All students →", which emits `PopoverWanted(&"students")`. Other roles: hidden.

Every string is a named const, including the role nouns. The script has `signal PopoverWanted(which: StringName)`, and `var university: University` and `var building: Building`. `_process` returns early unless it's visible and both are set.

- [ ] **Step 5: `Hud` hosts it**

In `hud.tscn`, add a `SidePanel` instance (unique) as a child of `Hud` right after `TopBar`, before `Popovers`, so the dropdowns draw over it.

In `hud.gd`:
- Add `@onready var sidePanel: SidePanel = %SidePanel`.
- Rename `_showBuilding` to `showBuilding`, and update its callers in `hud.gd`.
- In `setup`:
  - `sidePanel.setUniversity(state.university)`
  - `controller.SelectionChanged.connect(sidePanel.showBuilding)`
  - `sidePanel.CloseRequested.connect(func() -> void: controller.select(null))`
  - `sidePanel.PopoverWanted.connect(openPopover)`
  - `sidePanel.BuildingWanted.connect(showBuilding)`
  - `BuildWanted` is connected in Task 6.
- Add:

```gdscript
const PaneConstruction: StringName = &"construction"


## Shows the pane a name stands for, by selecting its first building and
## moving the camera to it; does nothing when there is no such building.
## Answers whether there was one. For the console and the keys.
func showPane(which: StringName) -> bool:
	var found: Building = _firstFor(which)
	if (found == null):
		return false
	showBuilding(found)
	return true


func _firstFor(which: StringName) -> Building:
	if (which == PaneConstruction):
		for building: Building in state.university.campus.buildings:
			if (building.underConstruction):
				return building
	return null
```

Tasks 4 and 5 add their names to `_firstFor`.

- [ ] **Step 6: `CampusView` loses `InfoPanel`**

In `campus_view.tscn`:
- Remove the `InfoPanel` instance and its `ext_resource`.
- Fix `load_steps` if the header has one.

In `campus_view.gd`:
- Remove `@onready var infoPanel` and `controller.SelectionChanged.connect(infoPanel.showBuilding)`.
- In `_onBuildingOpened`, remove the `if (building == controller.selected): infoPanel.showBuilding(building)` lines. The side panel polls, so it needs nothing. Keep `viewFor(building).setUnderConstruction(false)`.

Delete the three `info_panel` files with `git rm`. Then grep `university/src`, `university/tests` and `CLAUDE.md` for `InfoPanel` and `info_panel`. CLAUDE.md is rewritten in Step 8; code must have none left.

- [ ] **Step 7: `hud construction`**

In `debug_commands.gd` `_hud`, before the popover branch, try `hud.showPane(StringName(which))`. If it answers true, print and return. Note that `popup` and `none` are handled before this. Update the `hud` command's description to list the pane names.

- [ ] **Step 8: REGISTER, RUN-TESTS, LAUNCH-CHECK**

Run RUN-TESTS: 228 in 22.

Run LAUNCH-CHECK:
1. `pause`, `build dorm 30 15 0`, `hud construction`, `screenshot`. Compare with `#pane-uc`:
   - The panel is docked right.
   - The header reads "Dorm", "RESIDENTIAL · 120 BEDS", with the info pill "Under construction · opens Spring, Year 1".
   - The rows are Beds "+120" (note "360 → 480"), Off campus "440 → 320" (note "55% → 40%, still above the threshold") and Upkeep "−$150K / mo".
   - The refund note names the dorm's price.
   - The footer reads "Demolish · refund $2.0M".
2. Click the side panel's Demolish button. Aim with `eval get_root().find_child("SidePanel", true, false).find_child("DemolishButton", true, false).global_position` and `.size`. Then run `buildings`: 7 buildings are left, and `state` shows the cash back at $50,000,000 with no selection. `screenshot`: the panel is gone.
3. `select 0`, `screenshot`: an open dorm shows the header "Dorm" and Demolish only, since there's no role pane yet.
4. With the panel open, `hud money`, `screenshot`: the Money dropdown draws over the side panel, and both are open.

LOOK at each screenshot.

- [ ] **Step 9: `CLAUDE.md`, then commit**

In `CLAUDE.md`, replace `InfoPanel` everywhere:
- Describe `SidePanel`: docked right, opens and closes with the selection, panes by role and construction, Demolish with `Campus.refundFor`, relayed jumps.
- Describe `Hud.showPane` and `showBuilding`.
- Update the in-game paragraph: "the bottom-right info panel shows …" becomes the side panel.
- Add `hud construction` to the console list.

```bash
git add -A university/src/ui university/src/views/campus_view.tscn university/src/views/campus_view.gd university/src/debug/debug_commands.gd CLAUDE.md
git status --short
git commit -m "$(cat <<'EOF'
Dock the side panel on selection, with the construction pane and Demolish

Co-Authored-By: Claude <the model you actually are> <noreply@anthropic.com>
EOF
)"
```

---

### Task 4: The Admissions pane

**Files:**
- Create:
  - `university/src/ui/admissions_pane.tscn` and `university/src/ui/admissions_pane.gd`
  - `university/src/ui/projection_text.gd`
- Modify:
  - `university/src/ui/side_panel.tscn` and `university/src/ui/side_panel.gd`
  - `university/src/ui/students_dropdown.gd` (uses `ProjectionText`)
  - `university/src/ui/hud.gd`
  - `university/src/ui/ui_theme.tres`
  - `CLAUDE.md`

**Interfaces:**
- **Consumes:**
  - `Policy.step*`, `PriceStep`, `GradeStep` and `minimumGrade`
  - `University.pricesAt`, `seatsToFillNextFall`, `graduatingByNextFall`, `expectedApplicants`, `expectedIntake`, `fallReports`, `nextFallStart` and `reputation`
  - `Stepper`
- **Produces:**
  - **`ProjectionText`:**
    - `seatsNote(university) -> String`: "N open + M graduating", or "M graduating"
    - `intakeNote(intake: Intake) -> String`: "entry grade ≈ 3.24", or "" for none
  - **`AdmissionsPane`**, and the pane name `&"admissions"`

- [ ] **Step 1: `ProjectionText`**

The Students dropdown already words the seats-to-fill note and the intake note (`OpenPlusGraduating`, `GraduatingFormat`, `IntakeNote`, and the `toFill > graduating` rule). The Admissions pane shows the same two notes, so they move to one place. Create `university/src/ui/projection_text.gd`:

```gdscript
class_name ProjectionText
## How next fall's projections are worded, for the Students dropdown and the
## Admissions Office pane alike.

const OpenPlusGraduating: String = "%s open + %s graduating"
const GraduatingFormat: String = "%s graduating"
const IntakeNote: String = "entry grade ≈ %.2f"


## What the seats to fill are made of. Past graduation, what is left beyond the
## graduating class is seats open by next fall; with none, only the graduates.
static func seatsNote(university: University) -> String:
	var toFill: int = university.seatsToFillNextFall()
	var graduating: int = university.graduatingByNextFall()
	if (toFill > graduating):
		return OpenPlusGraduating % [NumberFormat.count(toFill - graduating), NumberFormat.count(graduating)]
	return GraduatingFormat % NumberFormat.count(graduating)


static func intakeNote(intake: Intake) -> String:
	return (IntakeNote % intake.entryGrade) if (intake.admitted > 0) else ""
```

In `students_dropdown.gd`, use `ProjectionText.seatsNote(university)` and `ProjectionText.intakeNote(intake)`. Delete the moved consts and the inline rule, and keep everything else.

- [ ] **Step 2: Theme**

Add to `ui_theme.tres`, following the mockup's `.pipe .st`, `.mini` and `.lever`:

| Variation | Base | Font / size | Colour | Style |
|---|---|---|---|---|
| `Stage` | PanelContainer | none | none | panel: chrome2, 1 px line border, radius 5, content margins 10/8 |
| `StageOn` | PanelContainer | none | none | the same with a gold border |
| `StageValue` | Label | BarlowSemiCondensed-SemiBold 20 | text | none |
| `StageCaption` | Label | BarlowSemiCondensed-Medium 11 | muted | none |
| `StageNote` | Label | BarlowSemiCondensed-Medium 11 | dim | none |
| `MiniBar` | Panel | none | none | panel: chrome3, no radius |
| `MiniBarOn` | Panel | none | none | panel: gold, no radius |
| `MiniLabel` | Label | BarlowSemiCondensed-Medium 10 | muted | none |
| `Lever` | PanelContainer | none | none | panel: chrome2, 1 px line border, radius 5, content margins 12/10 |
| `LeverTitle` | Label | Barlow-SemiBold 14 | text | none |

- [ ] **Step 3: `AdmissionsPane` scene**

`university/src/ui/admissions_pane.tscn` has root `AdmissionsPane` (VBoxContainer, separation 14, script `admissions_pane.gd`). Its children, following `#pane-admissions`:

1. **`Intake`** (VBoxContainer, separation 8):
   - `IntakeHeader` (HBoxContainer): `IntakeTitle` (Label, unique, `SectionTitle`, `uppercase`), a spacer, and a `SectionNote` "at today's reputation and next year's prices"
   - `Stages` (HBoxContainer, separation 6), three stages, each size flags 3:
     - `SeatsStage` (PanelContainer, `StageOn`) → VBox of `SeatsValue` (`StageValue`), a `StageCaption` "Seats to fill", and `SeatsDetail` (`StageNote`, autowrap)
     - `ApplicantsStage` (`Stage`) → `ApplicantsValue`, "Expected applicants", `ApplicantsDetail`
     - `IntakeStage` (`Stage`) → `IntakeValue`, "Expected intake", `IntakeDetail`

     All value and detail labels are unique. Captions are `uppercase`.
   - A `Note` (autowrap): "Seats fill from the top of the applicant list. How many apply depends on reputation and on the total price. Empty seats are upkeep with no tuition."
2. **`History`** (VBoxContainer, separation 6):
   - a `SectionTitle` "Applicants per fall" (uppercase)
   - `Chart` (HBoxContainer, unique, separation 5, `custom_minimum_size.y = 80`)
   - `NoFallsNote` (Label, unique, `Note`, text "No fall admission yet.", hidden)
3. **`Levers`** (VBoxContainer, separation 8):
   - `LeversHeader` (HBoxContainer): a `SectionTitle` "Levers", a spacer, and `ApplyNote` (Label, unique, `SectionNote`)
   - `MinimumLever` (PanelContainer, `Lever`) → VBox (separation 6) of a `LeverTitle` "Minimum entry grade", `MinimumStepper` (`stepper.tscn`, unique), and a `Note` (autowrap): "Off: every seat that has an applicant fills, and the entry grade follows how many apply. Raise it to leave seats empty in a weak year: tuition now against reputation later."
   - `TuitionLever` (`Lever`) → VBox of a `LeverTitle` "Tuition per semester", `TuitionNow` (Label, unique, `Note`), and `TuitionStepper` (unique)
   - `HousingLever` (`Lever`) → VBox of a `LeverTitle` "Room and meal plan per semester", `HousingNow` (Label, unique, `Note`), `RoomStepper` (unique), `MealStepper` (unique), and `TotalNote` (Label, unique, `Note`, autowrap)
4. **`Jumps`** (HBoxContainer, separation 6): `StudentsJump` ("Students →") and `FinancesJump` ("Finances →"), both unique, `JumpButton`, `focus_mode = 0`

- [ ] **Step 4: `AdmissionsPane` script**

`university/src/ui/admissions_pane.gd` follows the pane pattern: `signal PopoverWanted(which: StringName)`, `var university: University`, `var building: Building`, and `_process` gated on `visible`.

**`_process` fills:**
- `IntakeTitle`: `"Next intake · %s" % GameCalendar.periodLabel(university.nextFallStart())`
- **The seats stage:** `"≈ %s" % count(seatsToFillNextFall())`, with the detail `ProjectionText.seatsNote(university)`.
- **The applicants stage:** `"≈ %s" % count(expectedApplicants())`, with the detail `"reputation %.0f · %s a semester" % [reputation, MoneyFormat.full(university.pricesAt(university.nextFallStart()).total())]`.
- **The intake stage:** `expectedIntake()`, as `"≈ %s"` of `admitted`, with the detail `ProjectionText.intakeNote(intake)`.
- `ApplyNote`: `"apply from %s" % GameCalendar.periodLabel(university.nextFallStart())`
- **The minimum stepper:** `MinimumStepper.display(MinimumCaption, …)`. The value is "Off" (dimmed) when `policy.minimumGrade <= 0`, and `"%.1f"` of it otherwise.
- `TuitionNow`: `"This year %s" % MoneyFormat.full(policy.current.tuition)`
- **The tuition stepper:** `TuitionStepper.display(NextYearCaption, MoneyFormat.full(policy.next.tuition), false)`
- `HousingNow`: `"This year %s · %s" % [full(current.room), full(current.mealPlan)]`
- **The room and meal steppers:** `RoomStepper` and `MealStepper` display `policy.next.room` and `policy.next.mealPlan`.
- `TotalNote`: `"Applicants weigh the total: %s a semester. Off-campus students pay tuition only." % MoneyFormat.full(university.pricesAt(university.nextFallStart()).total())`

**`_ready` connects:**
- the steppers' `Stepped` to `university.policy.stepMinimum`, `stepNextTuition`, `stepNextRoom` and `stepNextMealPlan`, through a lambda that checks `university != null`
- the jumps, which emit `PopoverWanted(&"students")` and `PopoverWanted(&"money")`

**`_rebuildChart`** runs on `visibility_changed` and on `SemesterStarted`, connected in a `setUniversity`-style setter or wherever `university` is set:
1. Free the old bars.
2. Take the last `ChartFalls` (5) `fallReports()`.
3. If there are none, show `NoFallsNote`.
4. Otherwise, for each report add:
   - a VBoxContainer (alignment end, size flags 3), holding a Label (`MiniLabel`, centred) with `count(report.applicants)`
   - a Panel (`MiniBar`, or `MiniBarOn` for the latest) with `custom_minimum_size.y = ChartHeight * applicants / most`, where `ChartHeight` is 56 and `most` is the largest applicants count shown, done as floats
   - a Label (`MiniLabel`) with `"Y%d" % GameCalendar.year(report.month)`

`ChartFalls` and `ChartHeight` are named consts. Every string is a named const.

The side panel sets `university` before the pane is shown. The simplest safe hook for `SemesterStarted` is a `setUniversity(shown)` method on the pane that `SidePanel.setUniversity` calls. Give every pane that needs a signal the same method.

- [ ] **Step 5: `SidePanel` shows it**

- In `side_panel.tscn`, add an `AdmissionsPane` instance (unique, hidden) under `Panes`.
- In `side_panel.gd`:
  - add `@onready var admissionsPane: AdmissionsPane = %AdmissionsPane`
  - relay its `PopoverWanted`
  - give it the university in `setUniversity`
  - `_paneFor`: an open building whose `info.role() == BuildingInfo.Role.Admissions` gets `admissionsPane`
  - `_showPane`: set each pane's visibility and `building`. Keep this as one loop over a typed list of the pane Controls, plus the per-type `building` assignment, rather than a growing copy-paste.
- In `hud.gd` `_firstFor`, add `&"admissions"`, which is the first of `campus.openWithRole(BuildingInfo.Role.Admissions)`.

- [ ] **Step 6: REGISTER, RUN-TESTS, LAUNCH-CHECK**

Run RUN-TESTS: 228 in 22.

Run LAUNCH-CHECK:
1. `pause`, `hud admissions`, `screenshot`. Compare with `#pane-admissions`:
   - The header reads "Admissions", "ADMINISTRATION · ADMISSION AND PRICES".
   - The stages read ≈ 200 ("200 graduating"), ≈ 499 ("reputation 62 · $18,284 a semester") and ≈ 200 ("entry grade ≈ 3.12").
   - The chart has one gold bar labelled Y1 (499). This is the start state's own fall report.
   - The levers read: Minimum "Off"; tuition "This year $9,606", next year $9,606; room and meal plan "This year $4,542 · $4,136", with the steppers at $4,542 and $4,136.
2. Click the tuition stepper's +. Aim through `find_child("AdmissionsPane", …).find_child("TuitionStepper", …).find_child("Up", …)`. `screenshot`:
   - next year reads $9,706
   - the total note reads $18,384
   - the applicants stage is lower, since the price went up
3. Click the minimum's +, then `screenshot`: it reads 2.8.

LOOK at each screenshot.

- [ ] **Step 7: `CLAUDE.md`, then commit**

Add to `CLAUDE.md`:
- the Admissions pane: next intake, the applicants per fall from `fallReports()`, and the levers as `Stepper`s calling `Policy.step*`, applying from next fall
- `ProjectionText`
- `hud admissions` in the console list

```bash
git add -A university/src/ui CLAUDE.md
git status --short
git commit -m "$(cat <<'EOF'
Add the Admissions Office pane: next intake, applicants per fall, the levers

Co-Authored-By: Claude <the model you actually are> <noreply@anthropic.com>
EOF
)"
```

---

### Task 5: The academic, dorm and dining panes

**Files:**
- Create:
  - `university/src/ui/academic_pane.tscn` and `university/src/ui/academic_pane.gd`
  - `university/src/ui/dorm_pane.tscn` and `university/src/ui/dorm_pane.gd`
  - `university/src/ui/dining_pane.tscn` and `university/src/ui/dining_pane.gd`
- Modify:
  - `university/src/ui/side_panel.tscn` and `university/src/ui/side_panel.gd`
  - `university/src/ui/hud.gd`
  - `university/src/ui/ui_theme.tres`
  - `CLAUDE.md`

**Interfaces:**
- **Consumes:**
  - `Campus.openWithRole`, `seats()`, `beds()` and `meals()`
  - `University`:
    - `students.enrolled()`, `openSeats()`, `lastIntakeGrade`
    - `graduatingByNextFall()`, `seatsToFillNextFall()`
    - `residentsOf`, `offCampus()`, `offCampusShare()`, `hasProblem`
    - `housed()`, `bedsOpeningNextSemester()`, `nextSemesterStart()`
    - `roomFeesOf`, `feesNow()`, `mealPlans()`, `unfed()`, `diningLoad()`
  - `UniversityRules.diningLimit`, `DiningHardLimit` and `OverflowThreshold`
  - `DiningLoadLine` and `DiningLoadLine.toneFor`, `BuildingText`
- **Produces:** the panes `AcademicPane`, `DormPane` and `DiningPane`, and the pane names `&"academic"`, `&"dorm"` and `&"dining"`

All three follow the pane pattern and `AdmissionsPane`'s shape: named consts, `_process` gated on `visible`, and jumps emitted as signals. Every KPI is a `kpi.tscn`, and every row an `info_row.tscn`.

- [ ] **Step 1: Theme**

Add `BuildingRow` (base Button) to `ui_theme.tres`, for the mockup's `.blist .b`:
- normal: transparent, 1 px line border, radius 4, margins 10/7
- hover and pressed: the same with a gold border
- focus: StyleBoxEmpty
- font: Barlow-Regular 13 in text colour

Also add `BuildingRowAdd` (base Button): the same styles, with the font colour gold.

- [ ] **Step 2: `AcademicPane`** (following `#pane-acad`)

**Scene** (VBoxContainer, separation 12):
- `Kpis` (HBox, separation 26): `StudentsKpi`, `OpenSeatsKpi` and `GradeKpi` (kpi instances, unique)
- a `SectionTitle` "Seats" with a `SectionNote` "all academic buildings"
- `SeatsBar` (MeterBar, unique, `custom_minimum_size.y = 12`, size flags h 3)
- `SeatsNote` (Label, unique, `Note`, autowrap)
- `ListTitle` (Label, unique, `SectionTitle`, uppercase)
- `List` (VBox, unique, separation 4)
- `AddButton` (Button, unique, `BuildingRowAdd`, text "+ Add an academic building", `focus_mode = 0`)
- `Jumps` (HBox): `StudentsJump` ("All students →") and `AdmissionsJump` ("Admissions →"), both unique

**`_process`:**
- `StudentsKpi`: `"%s / %s" % [count(enrolled), count(campus.seats())]`, caption "Students / seats"
- `OpenSeatsKpi`: `count(openSeats())`
- `GradeKpi`: `"%.2f" % lastIntakeGrade`, caption "Entry grade"
- `SeatsBar`: enrolled / seats (0 when there are no seats), Good tone, no marks, `NoLimit`
- `SeatsNote`: `"%s students graduate before next fall, so next fall can take about %s with the buildings you have. Full classes are fine." % [count(graduatingByNextFall()), count(seatsToFillNextFall())]`
- `ListTitle`: `"Academic buildings · %d" % the list's count`

**`_rebuildList`** runs on `visibility_changed` and when the building changes. For each of `campus.openWithRole(BuildingInfo.Role.Academic)` it adds a Button (`BuildingRow`, `focus_mode = 0`, `alignment` left) whose text is `"%s   %s · %s / mo" % [name, BuildingText.holds(info), MoneyFormat.short(info.upkeep)]`. Pressing it emits `BuildingWanted(that building)`. A button's text keeps it simple; there's no need for child labels.

**Signals:**
- `AddButton` emits `BuildWanted(building.info.category)`.
- `StudentsJump` emits `PopoverWanted(&"students")`.
- `AdmissionsJump` emits `BuildingWanted` with the first open admissions office. It's hidden when there is none.

- [ ] **Step 3: `DormPane`** (following `#pane-dorm`)

**Scene:**
- `Kpis`: `FilledKpi` and `OffCampusKpi`
- a `SectionTitle` "Housing"
- `AllDormsRow` and `OpeningRow`
- `HousingNote` (Note, autowrap)
- a `SectionTitle` "Money"
- `RoomFeesRow` and `UpkeepRow`
- `PriceNote` (Note, autowrap), text "The room price is set for the whole university in the Admissions Office."
- `Jumps`: `HousingJump` ("All housing →")

**`_process`:**
- `FilledKpi`: `"%s / %s" % [count(residentsOf(building)), count(info.beds)]`, caption "Beds filled"
- `OffCampusKpi`: `count(offCampus())`, caption `"Off campus · %s" % percent(offCampusShare())`. Warn when `hasProblem(HousingOverflow)`.
- `AllDormsRow`: "All dorms", `"%s / %s beds" % [count(housed()), count(campus.beds())]`
- `OpeningRow`: `"Opening %s" % periodLabel(nextSemesterStart())`, `"+%s beds" % count(bedsOpeningNextSemester())`. Hidden when that's 0.
- `HousingNote`: `"With more students than beds, the rest live off campus and pay tuition only. Past %s off campus, satisfaction drops." % percent(OverflowThreshold)`
- `RoomFeesRow`: "Room fees per semester", `signed(roomFeesOf(building))`, Good, with the note `"%s × %s" % [count(residentsOf(building)), full(policy.current.room)]`
- `UpkeepRow`: "Upkeep and staff", `signed(-info.upkeep) + " / mo"`, Bad

**Signals:** `HousingJump` emits `PopoverWanted(&"housing")`.

- [ ] **Step 4: `DiningPane`** (following `#pane-dining`)

**Scene:**
- `Kpis`: `PlansKpi`, `LoadKpi` and `UnfedKpi`
- a `SectionTitle` "Load" with a `SectionNote` "all dining halls · housed students"
- `LoadLine` (a `dining_load_line.tscn` instance, unique)
- `LoadNote` (Note, autowrap)
- a `SectionTitle` "Money"
- `MealFeesRow` and `UpkeepRow`
- `Jumps`: `BuildJump` ("Build a dining hall →")

**`_process`:**
- `PlansKpi`: `count(mealPlans())`, caption "Meal plans"
- `LoadKpi`: `percent(diningLoad())`, caption "Load", tone `DiningLoadLine.toneFor(university)`
- `UnfedKpi`: `count(unfed())`, caption "Can't eat". Bad when `unfed() > 0`, else Normal.
- `LoadLine.display(university)`
- `LoadNote`: `"Up to %s diners it is comfortable. Past that it gets crowded and satisfaction drops. Past %s (%s) the rest can't eat: they buy no meal plan and satisfaction drops harder." % [count(campus.meals()), count(diningLimit(campus.meals())), percent(DiningHardLimit)]`
- `MealFeesRow`: "Meal plan fees per semester", `signed(feesNow().meals)`, Good
- `UpkeepRow`: "Upkeep and staff", `signed(-info.upkeep) + " / mo"`, Bad

**Signals:** `BuildJump` emits `BuildWanted(building.info.category)`.

- [ ] **Step 5: `SidePanel` and `Hud`**

- Add the three instances (unique, hidden) under `Panes`.
- Relay their signals, and give them the university.
- `_paneFor` maps each role to its pane: Academic → `academicPane`, Housing → `dormPane`, Dining → `diningPane`, Admissions → `admissionsPane`, Other → null.
- `_showPane` shows exactly one pane.
- In `hud.gd` `_firstFor`, add `&"academic"`, `&"dorm"` and `&"dining"`, each the first of `openWithRole` for its role.

- [ ] **Step 6: REGISTER, RUN-TESTS, LAUNCH-CHECK**

Run RUN-TESTS: 228 in 22.

Run LAUNCH-CHECK with `pause`, then:
1. `hud academic`, `screenshot`. Compare with `#pane-acad`:
   - the KPIs read 800 / 800, 0 and 3.12
   - the bar is full and green
   - the note says "200 students graduate before next fall, so next fall can take about 200"
   - the list shows two Engineering rows reading "400 seats · $210K / mo", then the add button
2. `hud dorm`, `screenshot`. Compare with `#pane-dorm`: 120 / 120; 440 · 55% in warn; All dorms 360 / 360 beds; room fees +$545K from 120 × $4,542; upkeep −$150K / mo.
3. `hud dining`, `screenshot`. Compare with `#pane-dining`: 360 meal plans, 55%, 0 can't eat, the bar, "Up to 650 … Past 845 (130%)", meal fees +$1.4M, upkeep −$220K / mo.
4. Click the dorm pane's "All housing →". The Housing dropdown opens beside the panel.

LOOK at each screenshot.

- [ ] **Step 7: `CLAUDE.md`, then commit**

Add to `CLAUDE.md`:
- the three panes, and what each reads
- the console names `academic`, `dorm` and `dining`

```bash
git add -A university/src/ui CLAUDE.md
git status --short
git commit -m "$(cat <<'EOF'
Add the academic, dorm and dining panes

Co-Authored-By: Claude <the model you actually are> <noreply@anthropic.com>
EOF
)"
```

---

### Task 6: The `BuildPanel` and `ActionBar`, replacing `BuildMenu`; keys B and X

**Files:**
- Create:
  - `university/assets/icons/hammer.svg` and `university/assets/icons/trash.svg`
  - `university/src/ui/action_bar.tscn` and `university/src/ui/action_bar.gd`
  - `university/src/ui/build_panel.tscn` and `university/src/ui/build_panel.gd`
- Modify:
  - `university/src/ui/hud.tscn` and `university/src/ui/hud.gd`
  - `university/src/views/campus_view.tscn` and `university/src/views/campus_view.gd`
  - `university/src/debug/debug_commands.gd`
  - `university/project.godot`
  - `university/src/ui/ui_theme.tres`
  - `CLAUDE.md`
- Delete: `university/src/ui/build_menu.tscn`, and `university/src/ui/build_menu.gd` with its `.uid`

**Interfaces:**
- **Consumes:**
  - `BuildingInfoDB.categories()` and `inCategory()`
  - `BuildingText.adds` and `footprint`
  - `Campus.canAfford`
  - `BuildController.armPlace`, `armDestroy`, `cancel`, `activeTool`, `placeInfo`, `ToolChanged` and `Tool`
- **Produces:**
  - **`BuildPanel`** (PanelContainer):
    - `signal BuildingChosen(info: BuildingInfo)`
    - `populate(db: BuildingInfoDB)`
    - `showCategory(category: String)`
    - `showAffordable(campus: Campus)`
    - `showTool(armed: BuildController.Tool, info: BuildingInfo)`
    - `university: University`
  - **`ActionBar`** (HBoxContainer):
    - signals `BuildPressed` and `DemolishPressed`
    - `showTool(armed: BuildController.Tool)`
    - `showBuildOpen(open: bool)`
  - **`Hud`:**
    - the popover `&"build"`
    - `openBuildPanel(category: String)`
    - `setup(gameState, gameCamera, buildController, buildingDB: BuildingInfoDB)`, which gains the building DB
  - **Input actions:** `ToggleBuild` (B) and `Demolish` (X)
  - **The console:** `hud build`

**How it behaves (controller's rulings):**
- The build panel is a popover: one at a time, closed by Esc or a world click.
- Choosing a card arms that type and **closes the panel**. The tool stays armed as today, one click per building, and a right click or Esc puts it away. The panel covers 900×430 of the campus, so placing with it open would hide the ground.
- Closing the panel no longer cancels the tool. The old list did, and it's gone.
- The ActionBar's Build button reads as pressed while the panel is open. Demolish reads as pressed while the destroy tool is armed.
- Demolish, or X, toggles the destroy tool: it arms it, or puts it away when it's already armed.
- B toggles the panel.
- While the semester popup shows, B and X are swallowed, like Space.
- Category colour squares and card thumbnails are left out. There is no colour data per category, and colours come only from the theme.

- [ ] **Step 1: Icons and the input actions**

Create `hammer.svg` and `trash.svg` in `university/assets/icons/`, with the same wrapper as the other icons: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">…</svg>`.
- `hammer.svg`: `<path d="M14 4l6 6-2 2-6-6z"/><path d="M12 6L4 14l3 3 8-8"/><path d="M4 20h7"/>`
- `trash.svg`: `<path d="M4 7h16M9 7V4h6v3M6 7l1 13h10l1-13"/>`

Run IMPORT.

In `university/project.godot` `[input]`, add `ToggleBuild` (physical keycode 66, B) and `Demolish` (physical keycode 88, X). Copy the exact entry format of `TogglePause`: `"deadzone": 0.2`, one `InputEventKey` with `"device":-1`, `"keycode":0` and the `"physical_keycode"`.

- [ ] **Step 2: Theme**

Add these variations to `ui_theme.tres`:

| Variation | Base | Font / size | Colour | Style |
|---|---|---|---|---|
| `ActionButton` | Button | BarlowSemiCondensed-SemiBold 11 | muted; pressed and hover-pressed font onGold | normal: chrome, 1 px line2 border, radius 6, shadow 16 at alpha 0.35. Hover: the same with a gold border. Pressed and hover-pressed: gold background and border. Focus: StyleBoxEmpty. Icon colours: normal text, pressed onGold. |
| `ActionKey` | Label | BarlowSemiCondensed-SemiBold 10 | dim | none |
| `BuildPanel` | PanelContainer | none | none | panel: chrome, 1 px line2 border, radius 6, shadow 40 at alpha 0.5, content margins 0 |
| `CategoryButton` | Button | Barlow-Medium 14 | text | normal: StyleBoxEmpty with margins 10/9. Hover: chrome2, radius 4. Pressed and hover-pressed: chrome3, radius 4, plus a 3 px gold left border (a StyleBoxFlat with `border_width_left = 3` in gold). Focus: StyleBoxEmpty. |
| `CategoryCount` | Label | BarlowSemiCondensed-Medium 11 | dim | none |
| `Card` | Button | none | none | normal: chrome2, 1 px line border, radius 5, margins 12/10. Hover, pressed and hover-pressed: the same with a gold border. Disabled: the normal style. Focus: StyleBoxEmpty. |
| `CardTitle` | Label | BarlowSemiCondensed-SemiBold 14 | text | none |
| `CardCost` | Label | BarlowSemiCondensed-SemiBold 14 | gold2 | none |
| `CardFx` | Label | Barlow-Regular 12 | muted | none |

A disabled card reads greyed. Its content labels are children, so the script sets the card's `modulate.a` to `DisabledAlpha` (0.45) while it's disabled, and back to 1 otherwise. That's a state-dependent visual with no literal Color.

Also remove the base `Button/styles/pressed` and `Button/styles/hover_pressed` entries, their two `StyleBoxFlat_armed*` sub_resources, and `Button/colors/font_pressed_color` and `font_hover_pressed_color`. They were kept for `BuildMenu`, which is being deleted. First grep every `.tscn` for a plain Button (with no `theme_type_variation`) that uses `toggle_mode`. If one exists, keep the entries and say so.

- [ ] **Step 3: `ActionBar`**

`university/src/ui/action_bar.tscn` has root `ActionBar` (HBoxContainer, separation 6, script `action_bar.gd`), anchored bottom-left: anchors left 0, top 1, bottom 1; offsets left 16, top −80, bottom −16. Its children are two Buttons, `BuildButton` and `DemolishButton` (unique), each with:
- `ActionButton`, 64×64, `toggle_mode = true`, `focus_mode = 0`
- `icon` hammer or trash, `icon_alignment = 1` (centre), `vertical_icon_alignment = 0` (top), `expand_icon = false`
- text "BUILD" or "DEMOLISH", authored in capitals, as the mockup's `.act` shows them. Button has no `uppercase` property.
- a child `Key` Label (`ActionKey`, `mouse_filter = 2`), text "B" or "X", anchored top-right at 4/6 px

`action_bar.gd`:

```gdscript
class_name ActionBar
extends HBoxContainer
## The two actions in the bottom-left corner: Build (B) opens the build panel,
## Demolish (X) arms the destroy tool. They only announce presses; the Hud and
## the controller own what is open and armed, and say so back.

signal BuildPressed
signal DemolishPressed

@onready var buildButton: Button = %BuildButton
@onready var demolishButton: Button = %DemolishButton


func _ready() -> void:
	buildButton.pressed.connect(func() -> void: BuildPressed.emit())
	demolishButton.pressed.connect(func() -> void: DemolishPressed.emit())


func showBuildOpen(open: bool) -> void:
	buildButton.set_pressed_no_signal(open)


func showTool(armed: BuildController.Tool) -> void:
	demolishButton.set_pressed_no_signal(armed == BuildController.Tool.Destroy)
```

- [ ] **Step 4: `BuildPanel`**

`university/src/ui/build_panel.tscn` has root `BuildPanel`:
- PanelContainer, `BuildPanel`, hidden, script `build_panel.gd`
- anchored bottom-left: anchors left 0, top 1, bottom 1; offsets left 16, right 916, top −520, bottom −90. That's 900×430, bottom 90.

Its child is `Split` (HBoxContainer, separation 0), which holds:
1. `Categories`: MarginContainer, margins 8/10/8/10, `custom_minimum_size.x = 190`. It holds `CategoryList` (VBox, unique, separation 2), whose first child is a `SectionTitle` "Build" (uppercase). The category buttons are added in code.
2. A `VSeparator`, which takes the theme's line2 default.
3. `Catalog`: MarginContainer, margins 14/12/14/12, size flags h 3. It holds a VBox (separation 10) of:
   - `Scroll`: ScrollContainer, v size flags 3, horizontal disabled, holding `Cards` (GridContainer, unique, `columns = 3`, h and v separation 8, size flags h 3)
   - an `HSeparator`
   - `Footer`: HBox, separation 12, holding `FootInfo` (Label, unique, `Note`), `FootWarn` (Label, unique, `NoteWarn`, hidden), a spacer, and `FootOpens` (Label, unique, `Note`)

**`build_panel.gd`:**

```gdscript
class_name BuildPanel
extends PanelContainer
## The build catalogue: categories from the Sheet's category column in the
## order they first appear, each with its count, and a card per type showing
## its cost, what it adds, its upkeep and its footprint. A card is greyed out
## while the campus cannot afford it and highlighted while armed. Choosing one
## only announces it; the controller arms it. Cards are made in code because
## how many there are is data.

signal BuildingChosen(info: BuildingInfo)

const CountFormat: String = "%d"
const FxFormat: String = "%s · upkeep %s / mo · %s"
const FxNoCapacityFormat: String = "upkeep %s / mo · %s"
const InfoFormat: String = "%s · %s · cash %s"
const WarnFormat: String = "borrow first, or wait for the %s fees"
const OpensFormat: String = "Placed now → under construction until %s starts"
const ChooseText: String = "Choose a building to place it."
const DisabledAlpha: float = 0.45
const CardHeight: float = 88.0

@onready var categoryList: VBoxContainer = %CategoryList
@onready var cards: GridContainer = %Cards
@onready var footInfo: Label = %FootInfo
@onready var footWarn: Label = %FootWarn
@onready var footOpens: Label = %FootOpens

var university: University

var _db: BuildingInfoDB
var _categoryButtons: Dictionary[String, Button]
var _cards: Dictionary[BuildingInfo, Button]
var _category: String = ""
var _armed: BuildingInfo
var _hovered: BuildingInfo
```

**`populate(db)`:**
- Store `db`.
- For each category of `db.categories()`, add a Button to `categoryList`: `CategoryButton`, `toggle_mode`, `focus_mode = 0`, `alignment` left, text = the category. Give it a child Label (`CategoryCount`, `mouse_filter = 2`, anchored right with an 8 px margin) whose text is `CountFormat % db.inCategory(category).size()`. Pressing it calls `showCategory(category)`.
- For every type, make a card Button: `Card`, `toggle_mode`, `focus_mode = 0`, `custom_minimum_size.y = CardHeight`, size flags h 3. Give it a VBox child (`mouse_filter = 2`, anchors full rect with 12/10 margins). The VBox holds:
  - an HBox of `CardTitle` (the name) and `CardCost` (`MoneyFormat.short(cost)`), right-aligned with a spacer
  - `CardFx`, autowrap, `mouse_filter = 2`: `FxFormat % [BuildingText.adds(info), MoneyFormat.short(info.upkeep), BuildingText.footprint(info)]`, or `FxNoCapacityFormat` when `adds` is empty
- On a card: `pressed` emits `BuildingChosen(info)`, `mouse_entered` sets `_hovered`, and `mouse_exited` clears it.
- Keep the cards in `_cards`, and add each to `cards` only while its category is shown.
- Finish with `showCategory(first category)`.

**`showCategory(category)`:**
- Set `_category`.
- Press only that category's button (`set_pressed_no_signal`).
- Show only its cards. The simplest way is to add every card to the grid once and toggle `visible` by `info.category`.

**`showAffordable(campus)`:** for each card, `disabled = not campus.canAfford(info)`, and `modulate.a` is `DisabledAlpha` when disabled, 1 otherwise.

**`showTool(armed, info)`:** set `_armed` to `info` while `armed == BuildController.Tool.Place`, else null, and `set_pressed_no_signal(entry == _armed)` on every card. A card press toggles the button the wrong way, and this puts it right.

**`_process`,** while visible and `university` is set, fills the footer from `_hovered`, or else `_armed`:
- With neither, `FootInfo` shows `ChooseText`, and `FootWarn` and `FootOpens` are hidden.
- Otherwise:
  - `FootInfo` shows `InfoFormat % [name, short(cost), short(university.finances.cash)]`.
  - `FootWarn` shows `WarnFormat % GameCalendar.PeriodNames[GameCalendar.period(university.nextSemesterStart())].to_lower()` while `not university.campus.canAfford(info)`.
  - `FootOpens` shows `OpensFormat % GameCalendar.periodLabel(university.nextSemesterStart())`.

- [ ] **Step 5: `Hud` routes it; `CampusView` drops `BuildMenu`**

**`hud.tscn`:**
- Add `ActionBar` (unique) as a child of `Hud` after `SidePanel`.
- Add `BuildPanel` (unique) under `Popovers`.

**`hud.gd`:**
- Add `@onready` vars for both.
- Add `&"build": buildPanel` to `_popovers`.
- In `openPopover` and `closePopover`, call `actionBar.showBuildOpen(_open == &"build")` after `_open` changes. This sits next to the existing `topBar.setOpen` calls.
- Change `setup` to `setup(gameState: GameState, gameCamera: GameCamera, buildController: BuildController, buildingDB: BuildingInfoDB)`, and add:
  - `buildPanel.university = state.university`
  - `buildPanel.populate(buildingDB)`
  - `buildPanel.showAffordable(state.university.campus)`
  - `state.university.finances.MoneyChanged.connect(func() -> void: buildPanel.showAffordable(state.university.campus))`
  - `buildPanel.BuildingChosen.connect(_armPlace)`
  - `actionBar.BuildPressed.connect(toggle.bind(&"build"))`
  - `actionBar.DemolishPressed.connect(_toggleDemolish)`
  - `controller.ToolChanged.connect(_onToolChanged)`
  - `sidePanel.BuildWanted.connect(openBuildPanel)`
- Add:

```gdscript
const PopoverBuild: StringName = &"build"


## Opens the build panel on one category, as the panes' "add a building" jumps do.
func openBuildPanel(category: String) -> void:
	openPopover(PopoverBuild)
	buildPanel.showCategory(category)


# Choosing a card arms it and puts the panel away, so the ground is clear to place on.
func _armPlace(info: BuildingInfo) -> void:
	controller.armPlace(info)
	closePopover()


# Demolish, the button or X, arms the destroy tool, or puts it away when armed.
func _toggleDemolish() -> void:
	if (controller.activeTool == BuildController.Tool.Destroy):
		controller.cancel()
	else:
		controller.armDestroy()


func _onToolChanged() -> void:
	buildPanel.showTool(controller.activeTool, controller.placeInfo)
	actionBar.showTool(controller.activeTool)
```

**Keys, in `hud.gd` `_unhandled_input`:**
- While the popup shows, swallow `ToggleBuild` and `Demolish` the way `TogglePause` is swallowed.
- Otherwise:
  - `ToggleBuild` → `toggle(PopoverBuild)`, marked handled
  - `Demolish` → `_toggleDemolish()`, marked handled

**`campus_view.tscn`:** remove the `BuildMenu` instance and its `ext_resource`, and fix `load_steps`.

**`campus_view.gd`:**
- Remove `@onready var buildMenu` and every `buildMenu.` line in `_ready`: `populate`, `showAffordable`, the `MoneyChanged` lambda, `BuildingChosen`, `DestroyChosen`, `Closed` and the `ToolChanged` lambda.
- Change the `setup` call to `hud.setup(gameState, camera, controller, Global.buildingDB)`.
- Leave the camera, views and highlights untouched.

Delete the three `build_menu` files with `git rm`. Then grep `university/src` and `university/tests` for `BuildMenu` and `build_menu`: none may be left.

- [ ] **Step 6: `hud build`**

`_hud` already routes unknown names to `openPopover`. Check that `hud build` opens the panel. Update the command's description.

- [ ] **Step 7: REGISTER, RUN-TESTS, LAUNCH-CHECK**

Run RUN-TESTS: 228 in 22.

Run LAUNCH-CHECK with `pause`, then:
1. `screenshot`: the two action buttons sit bottom-left, reading BUILD with its B and DEMOLISH with its X.
2. `hud build`, `screenshot`. Compare with `#build`:
   - The categories read Administration, Residential, Academic and Dining, in sheet order, each with count 1.
   - Administration is selected and shows the Admissions card: "$1.0M", "upkeep $90K / mo · 20 × 12 m".
   - The footer reads "Choose a building to place it."
   - The Build button reads as pressed.
3. Click the "Academic" category button, then `screenshot`. The Engineering card shows "+400 seats · upkeep $210K / mo · 40 × 24 m".
4. Click the Engineering card. Then `state`: the tool is `engineering_1`. `screenshot`: the panel is closed, the Build button is released, and a ghost follows the synthetic mouse if you `mousemove` over the ground.
5. `action Demolish down` and `up`, then `state`: the destroy tool. Again: none. `action ToggleBuild down` and `up`, then `screenshot`: the panel opens.
6. `money 1000000`, `hud build`, click Academic, `screenshot`. The Engineering card is greyed. Hover it (`mousemove` onto it): the footer shows the warn part "borrow first, or wait for the spring fees".

LOOK at each screenshot.

- [ ] **Step 8: `CLAUDE.md`, then commit**

In `CLAUDE.md`:
- Replace every `BuildMenu` description with `BuildPanel` (categories, cards, affordability, the armed highlight, the footer, choosing closes it) and `ActionBar` (Build B, Demolish X).
- Say that `Hud.setup` takes the building DB.
- Update the in-game paragraph ("The `Build` button in the bottom-left corner opens the list …"):
  - B or Build opens the build panel
  - a card arms it, and the panel closes
  - X or Demolish toggles the destroy tool
  - a right click or Esc still puts the tool away
- Add `hud build` to the console list.

```bash
git add -A university/src/ui university/assets/icons university/src/views/campus_view.tscn university/src/views/campus_view.gd university/src/debug/debug_commands.gd university/project.godot CLAUDE.md
git status --short
git commit -m "$(cat <<'EOF'
Replace the build list with the build panel and the action bar; B and X

Co-Authored-By: Claude <the model you actually are> <noreply@anthropic.com>
EOF
)"
```

---

### Task 7: Alerts

**Files:**
- Create:
  - `university/src/ui/alerts.tscn` and `university/src/ui/alerts.gd`
  - `university/src/ui/alert_row.tscn` and `university/src/ui/alert_row.gd`
- Modify:
  - `university/src/ui/hud.tscn` and `university/src/ui/hud.gd`
  - `university/src/ui/ui_theme.tres`
  - `CLAUDE.md`

**Interfaces:**
- **Consumes:**
  - `AlertFeed` and `AlertEntry` (Task 2)
  - `University.problems()`, `Finances.AutoBorrowed(shortfall, fee)`, `Campus.BuildingOpened(building)`
  - `GameState.week()`, `GameCalendar.weekInPeriod`
- **Produces:**
  - **`Alerts`** (VBoxContainer):
    - `signal PlaceWanted(entry: AlertEntry)`
    - `setup(gameState: GameState)`
  - **`Hud.openProblem(kind: Problem.Kind)`**, where a problem's alert and its marker (Task 8) lead to:
    - HousingOverflow → the Housing dropdown
    - DiningCrowded and DiningUnfed → the first open dining hall's pane, or the Housing dropdown with none
    - CreditMaxed → the Money dropdown

**How it behaves (spec):**
- Alerts stack top-right, under the bar.
- Each line shows the week it first appeared ("wk 3", `GameCalendar.weekInPeriod` of the entry's week), its text, and ×.
- Clicking a line opens its place:
  - a problem → `openProblem`
  - AutoBorrowed → the Money dropdown
  - Opened → that building's pane, if it still stands
- × dismisses the line, following `AlertFeed`'s rules.
- While the side panel is open, the alerts sit to its left.
- Texts and tones:

| Source | Text | Tone |
|---|---|---|
| HousingOverflow | "%s students without on-campus housing (%s)", from count and share | Bad |
| DiningCrowded | "Dining at %s of its recommended load: crowded" | Warn |
| DiningUnfed | "%s students can't eat" | Bad |
| CreditMaxed | "Credit line used up" | Bad |
| AutoBorrowed | "Monthly bill short by %s: borrowed automatically (+%s fee)" | Warn |
| Opened | "%s opened" | Info |

- The `Problem` fields hold the numbers: HousingOverflow's `count` and `fraction` are the off-campus students and share, DiningUnfed's `count` is the unfed, and Dining's `fraction` is the load.

- [ ] **Step 1: Theme**

Add to `ui_theme.tres`, following the mockup's `.alert`:
- `AlertBox` (PanelContainer): chrome, 1 px line2 border, radius 4, shadow 16 at alpha 0.35, content margins 0
- `AlertText` (Label): Barlow-Regular 13, text colour
- `AlertWhen` (Label): BarlowSemiCondensed-Medium 11, dim
- `AlertClose` (Button): Barlow-Regular 16, dim with hover text. StyleBoxEmpty for normal, hover, pressed and focus, with 2 px margins.
- `AlertAccentWarn`, `AlertAccentBad` and `AlertAccentInfo` (Panel): a flat warn, bad or info fill with radius 0

- [ ] **Step 2: `AlertRow`**

`university/src/ui/alert_row.tscn` has root `AlertRow` (PanelContainer, `AlertBox`, script `alert_row.gd`, `size_flags_horizontal = 8` so it hugs the right). Its child is an HBox (separation 0) of:
- `Content`: MarginContainer, margins 12/8/10/8, holding an HBox (separation 10) of:
  - `When`: Label, unique, `AlertWhen`
  - `Text`: Label, unique, `AlertText`. The row's width follows the text; every alert text in the table below is short enough.
  - `Close`: Button, unique, `AlertClose`, text "×", `focus_mode = 0`
- `Accent`: Panel, unique, `custom_minimum_size.x = 3`, `size_flags_vertical = 3`, `mouse_filter = 2`

`alert_row.gd`:

```gdscript
class_name AlertRow
extends PanelContainer
## One alert line: when it appeared, what it says, and ×. Clicking the line
## asks for its place; × asks to dismiss it.

signal Activated
signal Dismissed

const WeekFormat: String = "wk %d"
const AccentBase: String = "AlertAccent"

@onready var whenLabel: Label = %When
@onready var textLabel: Label = %Text
@onready var closeButton: Button = %Close
@onready var accent: Panel = %Accent

var entry: AlertEntry


func _ready() -> void:
	closeButton.pressed.connect(func() -> void: Dismissed.emit())
	gui_input.connect(_onGuiInput)


## accentName is "Warn", "Bad" or "Info".
func display(text: String, week: int, accentName: String) -> void:
	textLabel.text = text
	whenLabel.text = WeekFormat % GameCalendar.weekInPeriod(week)
	accent.theme_type_variation = StringName(AccentBase + accentName)


func _onGuiInput(event: InputEvent) -> void:
	var click: InputEventMouseButton = event as InputEventMouseButton
	if (click != null and click.pressed and click.button_index == MOUSE_BUTTON_LEFT):
		Activated.emit()
		accept_event()
```

- [ ] **Step 3: `Alerts`**

`university/src/ui/alerts.tscn` has root `Alerts`:
- VBoxContainer, separation 6, script `alerts.gd`, `mouse_filter = 2`
- anchors left 1, right 1, top 0; offsets right −16, top 72, left −16
- `grow_horizontal = 0` (grow left), `alignment` end

The rows are added in code.

`alerts.gd`:
- `var feed: AlertFeed = AlertFeed.new()`, `var state: GameState`, `var _rows: Array[AlertRow]` and `const RowScene: PackedScene = preload("res://src/ui/alert_row.tscn")`. Use `preload` here; the codebase preloads scenes in `global.gd`.
- `setup(gameState)`: store it, then connect:
  - `state.university.finances.AutoBorrowed` to a function that builds an `AlertEntry(AutoBorrowed, state.week())` with `amount` and `fee`, then calls `feed.addEvent`
  - `state.university.campus.BuildingOpened` to one that builds an `AlertEntry(Opened, state.week())` with `building`

  These fire mid-tick, and the handlers only add to the feed, which is safe.
- `_process`:
  1. `feed.update(state.university.problems(), state.week())`, then `var lines: Array[AlertEntry] = feed.shown()`.
  2. Rebuild the rows only when `lines` differs from what they show, by count or by entry identity. Freed rows use `queue_free`.
  3. Then, every frame, call `row.display(_textFor(entry), entry.week, _accentFor(entry))`, since counts change.
  4. Each row's `Activated` emits `PlaceWanted(entry)`, and its `Dismissed` calls `feed.dismiss(entry)`.
- `_textFor(entry)` and `_accentFor(entry)` follow the table above, with every string a named const. `_accentFor` answers `"Warn"`, `"Bad"` or `"Info"`, also as named consts.

- [ ] **Step 4: `Hud`**

**`hud.tscn`:** add `Alerts` (unique) after `SidePanel` and before `ActionBar`/`Popovers`, so dropdowns draw over alerts.

**`hud.gd`:**
- `setup`: `alerts.setup(state)` and `alerts.PlaceWanted.connect(_openPlace)`.
- `_process`: shift the alerts left of the side panel while it's open. Use `alerts.offset_right = -(AlertsMargin + (sidePanel.size.x if (sidePanel.visible) else 0.0))`, with `const AlertsMargin: float = 16.0`. Do the same for `offset_left`, so the anchors hold.
- Add:

```gdscript
## Where a problem is dealt with: its dropdown, or its building's pane.
func openProblem(kind: Problem.Kind) -> void:
	match kind:
		Problem.Kind.HousingOverflow:
			openPopover(PopoverHousing)
		Problem.Kind.DiningCrowded, Problem.Kind.DiningUnfed:
			if (not showPane(PaneDining)):
				openPopover(PopoverHousing)
		Problem.Kind.CreditMaxed:
			openPopover(PopoverMoney)


func _openPlace(entry: AlertEntry) -> void:
	match entry.source:
		AlertEntry.Source.Problem:
			openProblem(entry.problem.kind)
		AlertEntry.Source.AutoBorrowed:
			openPopover(PopoverMoney)
		AlertEntry.Source.Opened:
			if (state.university.campus.buildings.has(entry.building)):
				showBuilding(entry.building)
```

Add the consts `PopoverHousing` (`&"housing"`) and `PopoverMoney` (`&"money"`) if `hud.gd` doesn't already have them, and `PaneDining` (`&"dining"`) as Task 5's name. Use them everywhere `hud.gd` spells those names.

- [ ] **Step 5: REGISTER, RUN-TESTS, LAUNCH-CHECK**

Run RUN-TESTS: 228 in 22.

Run LAUNCH-CHECK with `pause`, then:
1. `screenshot`: one alert, top-right: "wk 1", "440 students without on-campus housing (55%)" with a bad accent, and ×.
2. Click the alert line (not ×). The Housing dropdown opens.
3. `hud none`, click ×, `screenshot`: the alert is gone.
4. `money 0`, `advance 1`, `screenshot`: the AutoBorrowed event reads "Monthly bill short by …: borrowed automatically (+… fee)" with a warn accent. The overflow alert stays hidden, since its condition never cleared.
5. `select 0`, `screenshot`: the alerts sit to the left of the side panel.

LOOK at each screenshot.

- [ ] **Step 6: `CLAUDE.md`, then commit**

Add to `CLAUDE.md`:
- `Alerts`, `AlertFeed` and `AlertEntry`: the rules, events from `AutoBorrowed` and `BuildingOpened`, and a click opens the place
- `Hud.openProblem`
- the in-game paragraph: alerts, top right

```bash
git add -A university/src/ui CLAUDE.md
git status --short
git commit -m "$(cat <<'EOF'
Show alerts for what is wrong and what just happened

Co-Authored-By: Claude <the model you actually are> <noreply@anthropic.com>
EOF
)"
```

---

### Task 8: Campus markers

**Files:**
- Create:
  - `university/src/ui/campus_markers.gd` (a Control added in `hud.tscn`)
  - `university/src/ui/campus_marker.tscn` and `university/src/ui/campus_marker.gd`
- Modify:
  - `university/src/ui/hud.tscn` and `university/src/ui/hud.gd`
  - `university/src/ui/ui_theme.tres`
  - `CLAUDE.md`

**Interfaces:**
- **Consumes:**
  - `Campus.centroid`, `openWithRole` and `buildings`
  - `University.hasProblem`, `offCampus()`, `offCampusShare()`, `diningLoad()`
  - `BuildingText.adds`
  - `Building.Height`
  - `Camera3D.unproject_position` and `is_position_behind` (both verified)
  - `Hud.openProblem` and `showBuilding`
- **Produces:** **`CampusMarkers`** (Control), with `setup(university: University, gameCamera: GameCamera)`, `signal ProblemWanted(kind: Problem.Kind)` and `signal BuildingWanted(building: Building)`

**How it behaves (spec):** markers are screen labels over 3D points, re-placed every frame.

| Marker | Point | Text | Small | Tone |
|---|---|---|---|---|
| HousingOverflow, while it holds | over the centroid of the open dorms | "%s off campus" | "%s · above %s", the share and the threshold | Bad |
| DiningCrowded or DiningUnfed | over the centroid of the open dining halls | "Dining at %s", the load | "crowded" or "can't eat" | Warn or Bad |
| each building under construction | over its position | "Opens %s", the period label | `BuildingText.adds(info)` | Info |

- Each point is lifted to `Building.Height`.
- A marker whose point is behind the camera hides.
- Clicking a problem marker calls `openProblem(kind)`. Clicking a construction marker shows that building's pane.

- [ ] **Step 1: Theme**

Add to `ui_theme.tres`, following the mockup's `.marker`:
- `MarkerBox` (PanelContainer): chrome, 1 px line2 border, radius 4, shadow 16 at alpha 0.35, content margins 0
- `MarkerText` (Label): BarlowSemiCondensed-SemiBold 13, text colour
- `MarkerSmall` (Label): BarlowSemiCondensed-Medium 13, muted
- `MarkerStem` (Panel): line2 fill
- The accent strips reuse Task 7's `AlertAccentWarn`, `AlertAccentBad` and `AlertAccentInfo`.

- [ ] **Step 2: `CampusMarker`**

`university/src/ui/campus_marker.tscn` has root `CampusMarker` (VBoxContainer, separation 0, `mouse_filter = 2`, script `campus_marker.gd`). Its children:
- `Box`: PanelContainer, unique, `MarkerBox`, default mouse_filter (STOP), holding an HBox (separation 0) of:
  - `Accent`: Panel, unique, 3 px wide, v size flags 3, `mouse_filter = 2`
  - a MarginContainer (margins 9/6/9/6) holding an HBox (separation 6) of `Text` (Label, unique, `MarkerText`) and `Small` (Label, unique, `MarkerSmall`)
- `Stem`: Panel, `MarkerStem`, `custom_minimum_size = Vector2(2, 22)`, `size_flags_horizontal = 4` (centred), `mouse_filter = 2`

`campus_marker.gd` mirrors `AlertRow`:
- `signal Activated`
- `display(text: String, small: String, accentName: String)`
- a `gui_input` handler on `Box` that emits `Activated` on a left press and accepts the event
- `func anchorAt(point: Vector2) -> void`, which sets `position = point - Vector2(size.x / 2.0, size.y)` so the stem's foot sits on the point

- [ ] **Step 3: `CampusMarkers`**

`campus_markers.gd`:

```gdscript
class_name CampusMarkers
extends Control
## Labels over the campus, where things need looking at: housing overflow over
## the dorms, dining trouble over the dining halls, and every building still
## going up. Re-placed every frame from the camera, so they follow panning and
## turning. Clicking one asks for its place.

signal ProblemWanted(kind: Problem.Kind)
signal BuildingWanted(building: Building)

const MarkerScene: PackedScene = preload("res://src/ui/campus_marker.tscn")
# ... every text a named const (see the table above).
```

`setup(university, gameCamera)` stores both.

**`_process` builds a list of wanted markers:**
1. A problem marker for HousingOverflow when `hasProblem`, at `Campus.centroid(openWithRole(Housing))`.
2. One for DiningUnfed or DiningCrowded, whichever holds, at the centroid of `openWithRole(Dining)`. Skip it when there are no dining halls.
3. One per building with `underConstruction`, at its `pos`.

Keep a pool of `CampusMarker` children, growing and hiding as needed, rather than freeing and adding every frame.

**For each wanted marker:**
- `var world: Vector3 = Vector3(point.x, Building.Height, point.y)`
- If `camera.is_position_behind(world)`, hide it.
- Otherwise show it, call `display(...)`, then `anchorAt(camera.unproject_position(world))`.

**Clicks:** each pooled marker's `Activated` emits `ProblemWanted(kind)` or `BuildingWanted(building)`, for the entry it shows *now*. Store the current entry on the marker (for example, `var problemKind: int` and `var building: Building` on `CampusMarker`), and read it in the handler.

Use `Problem.Kind` for the kind wherever the typed signal needs it. `ProblemWanted` takes `Problem.Kind`, so the stored value must be typed `Problem.Kind`, not `int`, because `int_as_enum_without_match` is an error.

- [ ] **Step 4: `Hud`**

**`hud.tscn`:** add a `CampusMarkers` Control (unique, full rect, `mouse_filter = 2`, script `campus_markers.gd`) as the **first** child of `Hud`, under everything else.

**`hud.gd` `setup`:**
- `campusMarkers.setup(state.university, camera)`
- `campusMarkers.ProblemWanted.connect(openProblem)`
- `campusMarkers.BuildingWanted.connect(showBuilding)`

- [ ] **Step 5: REGISTER, RUN-TESTS, LAUNCH-CHECK**

Run RUN-TESTS: 228 in 22.

Run LAUNCH-CHECK with `pause`, then:
1. `screenshot`. One marker, "440 off campus · 55% · above 25%", stands over the three dorms, with a bad accent and a stem.
2. `build dorm 30 15 0`, `screenshot`. A second marker, "Opens Spring, Year 1 · +120 beds", stands over the new dorm with an info accent.
3. `camera 0 0 200 135`, `screenshot`. The markers follow the turned view.
4. Click the construction marker. Aim through `find_child("CampusMarkers", …)`'s children, reading each marker's `global_position` and `size`. The side panel opens on the new dorm's construction pane.

LOOK at each screenshot.

- [ ] **Step 6: `CLAUDE.md`, then commit**

Add to `CLAUDE.md`: `CampusMarkers` and what they show, where they stand (the centroid lifted to `Building.Height`, `unproject_position`, hidden when behind the camera), and what a click opens.

```bash
git add -A university/src/ui CLAUDE.md
git status --short
git commit -m "$(cat <<'EOF'
Mark campus problems and buildings going up, over the campus itself

Co-Authored-By: Claude <the model you actually are> <noreply@anthropic.com>
EOF
)"
```

---

### Task 9: Tab, F2 and F3; the last jumps; the console names

**Files:**
- Modify:
  - `university/project.godot`
  - `university/src/ui/hud.gd`
  - `university/src/ui/housing_dropdown.tscn` and `university/src/ui/housing_dropdown.gd`
  - `university/src/debug/debug_commands.gd`
  - `CLAUDE.md`

**Interfaces:**
- **Input actions:** `UniversityMenu` (Tab), `AdmissionsPane` (F2), `MoneyPanel` (F3)
- **The Housing dropdown:** its "Room & meal plan prices →" jump emits a new `AdmissionsJumped`, replacing `MoneyJumped`. It's disabled while no Admissions Office is open.
- **The console:** `hud <name>` prints an error for a name it doesn't know.

- [ ] **Step 1: The input actions**

In `university/project.godot` `[input]`, add these, in the same format as `TogglePause`:
- `UniversityMenu`, physical keycode 4194306 (Tab)
- `AdmissionsPane`, 4194333 (F2)
- `MoneyPanel`, 4194334 (F3)

- [ ] **Step 2: `Hud` reads them**

In `_unhandled_input`, swallow the three while the popup shows, as in Task 6. Otherwise, each is marked handled and does this:
- `UniversityMenu` → `toggle(PopoverUniversity)`, where `PopoverUniversity` is `&"unimenu"`
- `AdmissionsPane` → `showPane(PaneAdmissions)`
- `MoneyPanel` → `toggle(PopoverMoney)`

Tab's focus walking doesn't apply, since every HUD control has `focus_mode = 0`. Check that pressing Tab reaches `_unhandled_input` (step 5).

- [ ] **Step 3: The Housing dropdown's prices jump**

In `housing_dropdown.gd`:
- Rename `MoneyJumped` to `AdmissionsJumped`.
- In `_process`, set the jump's `disabled = not university.campus.hasOpenAdmissionsOffice()`.

In `hud.gd`, connect `housingDropdown.AdmissionsJumped` to a lambda calling `showPane(PaneAdmissions)`. Remove the old `MoneyJumped` connection.

- [ ] **Step 4: `hud <name>` names**

In `debug_commands.gd` `_hud`, a name that is none of `none`, `popup`, a pane (`hud.showPane` answering true), or a popover prints `"Unknown HUD name: %s"` (a named const) and changes nothing.
- For the popover check, add `Hud.hasPopover(which: StringName) -> bool`, which is `_popovers.has(which)`.
- Update the command's description to list every name.

- [ ] **Step 5: REGISTER, RUN-TESTS, LAUNCH-CHECK**

Run RUN-TESTS: 228 in 22.

Run LAUNCH-CHECK with `pause`, then:
1. `action UniversityMenu down` and `up`, then `screenshot`: the University menu is open, and its F2 and F3 labels are now real.
2. `action AdmissionsPane down` and `up`, then `screenshot`: the Admissions pane shows, and the camera has moved to the office.
3. `action MoneyPanel down` and `up`, then `screenshot`: Money is open beside the Admissions pane.
4. `hud housing`, then click "Room & meal plan prices →". The Admissions pane shows.
5. `hud nonsense`: the console prints the unknown-name error.

LOOK at each screenshot.

- [ ] **Step 6: `CLAUDE.md`, then commit**

**In-game paragraph.** Make it describe the whole HUD as built:
- the keys: B, X, Tab, F2, F3, F5, F9, Space, +/− and Esc (in its order)
- the side panel
- the build panel and action bar
- alerts and markers

Remove anything left over from the old build list or info panel.

**Console list.** It must match the `_init` registration order and the `hud` names.

```bash
git add university/project.godot university/src/ui/hud.gd university/src/ui/housing_dropdown.tscn university/src/ui/housing_dropdown.gd university/src/debug/debug_commands.gd CLAUDE.md
git commit -m "$(cat <<'EOF'
Bind Tab, F2 and F3, point the prices jump at Admissions, and name every HUD part

Co-Authored-By: Claude <the model you actually are> <noreply@anthropic.com>
EOF
)"
```
